# Generated by Django 3.2.5 on 2021-08-31 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('district', '0001_initial'),
        ('city', '0002_auto_20210809_1319'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cities_district', to='district.district', verbose_name='Район'),
        ),
        migrations.AddField(
            model_name='city',
            name='link',
            field=models.CharField(default='', max_length=50, verbose_name='Ссылка для парсинга'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='city',
            name='man_procent',
            field=models.CharField(default='', max_length=50, verbose_name='Процент мужчин'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='city',
            name='total_candidate',
            field=models.CharField(default='', max_length=50, verbose_name='Всего кандидатов'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='city',
            name='total_er',
            field=models.CharField(default='', max_length=50, verbose_name='Всего из Единой России'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='city',
            name='total_kprf',
            field=models.CharField(default='', max_length=50, verbose_name='Всего из КПРФ'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='city',
            name='total_ldpr',
            field=models.CharField(default='', max_length=50, verbose_name='Всего из ЛДПР'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='city',
            name='total_place',
            field=models.CharField(default='', max_length=50, verbose_name='Всего мест'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='city',
            name='total_self',
            field=models.CharField(default='', max_length=50, verbose_name='Всего самовыдвиженцев'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='city',
            name='total_sr',
            field=models.CharField(default='', max_length=50, verbose_name='Всего из Справедливой России'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='city',
            name='total_voters',
            field=models.CharField(default='', max_length=50, verbose_name='Всего избирателей'),
            preserve_default=False,
        ),
    ]
