# Generated by Django 2.2.16 on 2020-11-11 12:12

from django.conf import settings
import django.contrib.postgres.indexes
from django.db import migrations, models
import django.db.models.deletion
import imagekit.models.fields
import users.helpers


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20201111_1212'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', imagekit.models.fields.ProcessedImageField(upload_to=users.helpers.upload_to_user_directory)),
                ('preview', imagekit.models.fields.ProcessedImageField(upload_to=users.helpers.upload_to_user_directory)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photo_creator', to=settings.AUTH_USER_MODEL, verbose_name='Создатель')),
                ('post', models.ManyToManyField(blank=True, related_name='item_photo', to='blog.ElectNew')),
            ],
            options={
                'ordering': ['-created'],
                'verbose_name': 'Фото',
                'verbose_name_plural': 'Фото',
            },
        ),
        migrations.CreateModel(
            name='Doc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('file', models.FileField(upload_to=users.helpers.upload_to_user_directory, verbose_name='Документ')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doc_creator', to=settings.AUTH_USER_MODEL, verbose_name='Создатель')),
                ('post', models.ManyToManyField(blank=True, related_name='item_doc', to='blog.ElectNew')),
            ],
            options={
                'ordering': ['-created'],
                'verbose_name': 'Документ',
                'verbose_name_plural': 'Документы',
            },
        ),
        migrations.AddIndex(
            model_name='photo',
            index=django.contrib.postgres.indexes.BrinIndex(fields=['created'], name='users_photo_created_426954_brin'),
        ),
        migrations.AddIndex(
            model_name='doc',
            index=django.contrib.postgres.indexes.BrinIndex(fields=['created'], name='users_doc_created_2c5747_brin'),
        ),
    ]
