# Generated by Django 2.2.16 on 2020-11-11 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20201111_1212'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='post',
        ),
        migrations.DeleteModel(
            name='Doc',
        ),
        migrations.DeleteModel(
            name='Photo',
        ),
    ]
