# Generated by Django 2.2.16 on 2020-11-11 19:01

from django.db import migrations
import imagekit.models.fields
import users.helpers


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20201111_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=imagekit.models.fields.ProcessedImageField(upload_to=users.helpers.upload_to_user_directory, verbose_name='Аватар'),
        ),
    ]
