# Generated by Django 3.1.5 on 2021-02-10 14:38

from django.db import migrations, models
import users.helpers


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20210209_1645'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='b_avatar',
            field=models.ImageField(blank=True, upload_to=users.helpers.upload_to_user_directory),
        ),
        migrations.AddField(
            model_name='user',
            name='s_avatar',
            field=models.ImageField(blank=True, upload_to=users.helpers.upload_to_user_directory),
        ),
    ]
