# Generated by Django 3.1.5 on 2021-02-13 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20210210_1438'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='device',
            field=models.CharField(blank=True, choices=[('De', 'Комп'), ('Ph', 'Телефон')], max_length=5, verbose_name='Оборудование'),
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('Man', 'Мужской'), ('Fem', 'Женский')], max_length=5, verbose_name='Пол'),
        ),
    ]
