# Generated by Django 3.2 on 2021-05-12 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_user_perm'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='perm',
            new_name='type',
        ),
    ]
