# Generated by Django 3.2 on 2021-05-14 16:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_rename_perm_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='comments',
            field=models.PositiveIntegerField(default=0, verbose_name='Кол-во комментов'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='communities',
            field=models.PositiveIntegerField(default=0, verbose_name='Кол-во групп'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='docs',
            field=models.PositiveIntegerField(default=0, verbose_name='Кол-во документов'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='elect_news',
            field=models.PositiveIntegerField(default=0, verbose_name='Кол-во постов'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='follows',
            field=models.PositiveIntegerField(default=0, verbose_name='Кол-во подписчиков'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='friends',
            field=models.PositiveIntegerField(default=0, verbose_name='Кол-во друзей'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='photos',
            field=models.PositiveIntegerField(default=0, verbose_name='Кол-во фотографий'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='surveys',
            field=models.PositiveIntegerField(default=0, verbose_name='Кол-во опросов'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='tracks',
            field=models.PositiveIntegerField(default=0, verbose_name='Кол-во аудиозаписей'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='videos',
            field=models.PositiveIntegerField(default=0, verbose_name='Кол-во видеозаписей'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='views',
            field=models.PositiveIntegerField(default=0, verbose_name='Кол-во просмотров постов'),
        ),
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('view', models.BooleanField(default=False, verbose_name='Просмотрено')),
                ('followed_user', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, related_name='followers', to=settings.AUTH_USER_MODEL, verbose_name='На кого подписывается')),
                ('user', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, related_name='follows', to=settings.AUTH_USER_MODEL, verbose_name='Подписчик')),
            ],
            options={
                'verbose_name': 'Подписчик',
                'verbose_name_plural': 'Подписчики',
                'unique_together': {('user', 'followed_user')},
            },
        ),
    ]
