# Generated by Django 3.2 on 2021-06-22 19:05

from django.db import migrations
import imagekit.models.fields
import users.helpers


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_alter_user_s_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='s_avatar',
            field=imagekit.models.fields.ProcessedImageField(blank=True, upload_to=users.helpers.upload_to_user_directory, verbose_name='Главное изображение'),
        ),
    ]
