# Generated by Django 3.2 on 2021-06-23 12:38

from django.db import migrations, models
import users.helpers


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_alter_user_s_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='s_avatar',
            field=models.ImageField(blank=True, upload_to=users.helpers.upload_to_user_directory),
        ),
    ]
