# Generated by Django 3.2.5 on 2021-08-01 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_auto_20210701_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deputatsend',
            name='text',
            field=models.TextField(blank=True, max_length=1000, verbose_name='Описание спообов идентификации'),
        ),
        migrations.AlterField(
            model_name='usersecretkey',
            name='key',
            field=models.CharField(blank=True, max_length=40, verbose_name='Ключ доступа'),
        ),
    ]
