# Generated by Django 3.2.5 on 2021-08-09 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_auto_20210803_1546'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserInfo',
        ),
    ]
