# Generated by Django 3.2.5 on 2021-09-04 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('district', '__first__'),
        ('users', '0025_auto_20210904_1725'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='district.district2', verbose_name='Районы, за которым закреплен депутат'),
        ),
    ]
