# Generated by Django 3.2.5 on 2021-10-05 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_user_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='theme',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Светлый фон'), (2, 'Темный фон')], default=1, verbose_name='Тема'),
        ),
    ]
