# Generated by Django 3.2.5 on 2021-10-08 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0027_userprofile_theme'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'Информация о пользователе ', 'verbose_name_plural': 'Информация о пользователях'},
        ),
    ]
