# Generated by Django 3.2.5 on 2021-11-17 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0030_auto_20211110_1800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprivate',
            name='old',
            field=models.BooleanField(default=False, verbose_name='Возраст открыт'),
        ),
    ]
