# Generated by Django 3.2 on 2021-05-13 18:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('communities', '0001_initial'),
        ('music', '0005_auto_20210510_1710'),
    ]

    operations = [
        migrations.AddField(
            model_name='music',
            name='community',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='track_community', to='communities.community', verbose_name='Сообщество'),
        ),
        migrations.AddField(
            model_name='soundlist',
            name='communities',
            field=models.ManyToManyField(blank=True, related_name='_music_soundlist_communities_+', to='communities.Community'),
        ),
        migrations.AddField(
            model_name='soundlist',
            name='community',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='playlist_community', to='communities.community', verbose_name='Сообщество'),
        ),
        migrations.AlterField(
            model_name='soundlist',
            name='creator',
            field=models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, related_name='playlist_creator', to=settings.AUTH_USER_MODEL, verbose_name='Создатель'),
        ),
        migrations.AlterField(
            model_name='soundlist',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='_music_soundlist_users_+', to=settings.AUTH_USER_MODEL),
        ),
    ]
