# Generated by Django 3.2 on 2021-06-03 15:39

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0010_alter_soundlist_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='music',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, verbose_name='uuid'),
        ),
    ]
