# Generated by Django 3.2 on 2021-06-03 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0011_music_uuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='music',
            name='uuid',
        ),
    ]
