# Generated by Django 3.2.5 on 2021-10-08 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0008_medialist'),
        ('music', '0013_auto_20211002_1535'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='music',
            name='media_list',
        ),
        migrations.AddField(
            model_name='music',
            name='media_list',
            field=models.ManyToManyField(blank=True, related_name='_music_music_media_list_+', to='lists.MediaList', verbose_name='Медиа-список'),
        ),
    ]
