# Generated by Django 3.2.5 on 2021-10-10 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0015_alter_music_media_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='music',
            name='is_track',
            field=models.BooleanField(default=True),
        ),
    ]
