# Generated by Django 3.2.5 on 2021-08-11 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0003_community_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='community',
            name='have_link',
        ),
        migrations.RemoveField(
            model_name='communityinfo',
            name='b_avatar',
        ),
        migrations.RemoveField(
            model_name='communityinfo',
            name='cover',
        ),
        migrations.RemoveField(
            model_name='communityinfo',
            name='description',
        ),
        migrations.AddField(
            model_name='community',
            name='description',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='communityinfo',
            name='dislike',
            field=models.PositiveIntegerField(default=0, verbose_name='Кол-во дизлайков'),
        ),
        migrations.AddField(
            model_name='communityinfo',
            name='inert',
            field=models.PositiveIntegerField(default=0, verbose_name='Кол-во inert'),
        ),
        migrations.AddField(
            model_name='communityinfo',
            name='like',
            field=models.PositiveIntegerField(default=0, verbose_name='Кол-во лайков'),
        ),
        migrations.AlterField(
            model_name='community',
            name='perm',
            field=models.CharField(choices=[('SU', 'Предложенное'), ('RE', 'Отклоненное'), ('ST', 'Обычные права'), ('VS', 'Запрос на проверку'), ('VE', 'Провернный')], default='ST', max_length=5, verbose_name='Уровень доступа'),
        ),
        migrations.AlterField(
            model_name='community',
            name='type',
            field=models.CharField(choices=[('MAN', 'Созданный персоналом'), ('PUB', 'Открытый'), ('_PRO', 'Обработка'), ('_DELO', 'Открытый удалённый'), ('_DELM', 'Менеджерский удалённый'), ('_BANO', 'Открытый баннер'), ('_BANM', 'Менеджерский баннер'), ('_SUSO', 'Открытый замороженный'), ('_SUSM', 'Менеджерский замороженный'), ('_BLOO', 'Открытый блокнутый'), ('_BLOM', 'Менеджерский блокнутый')], default='_PRO', max_length=5),
        ),
        migrations.DeleteModel(
            name='CommunityFollow',
        ),
    ]
