# Generated by Django 3.2.5 on 2021-08-12 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0004_auto_20210811_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='perm',
            field=models.CharField(choices=[('_SU', 'Предложенное'), ('_RE', 'Отклоненное'), ('ST', 'Обычные права'), ('VS', 'Запрос на проверку'), ('VE', 'Провернный')], default='ST', max_length=5, verbose_name='Уровень доступа'),
        ),
    ]
