# Generated by Django 3.2.5 on 2021-09-04 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0005_alter_community_perm'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='community',
            name='city',
        ),
    ]
