# Generated by Django 3.2.11 on 2022-02-06 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0006_remove_community_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='communitynotificationsgood',
            name='community',
        ),
        migrations.RemoveField(
            model_name='communitynotificationsmusic',
            name='community',
        ),
        migrations.RemoveField(
            model_name='communitynotificationsphoto',
            name='community',
        ),
        migrations.RemoveField(
            model_name='communitynotificationspost',
            name='community',
        ),
        migrations.RemoveField(
            model_name='communitynotificationsvideo',
            name='community',
        ),
        migrations.RemoveField(
            model_name='communityprivategood',
            name='community',
        ),
        migrations.RemoveField(
            model_name='communityprivatemusic',
            name='community',
        ),
        migrations.RemoveField(
            model_name='communityprivatephoto',
            name='community',
        ),
        migrations.RemoveField(
            model_name='communityprivatepost',
            name='community',
        ),
        migrations.RemoveField(
            model_name='communityprivatevideo',
            name='community',
        ),
        migrations.RemoveField(
            model_name='communitysectionsopen',
            name='community',
        ),
        migrations.DeleteModel(
            name='CommunityInfo',
        ),
        migrations.DeleteModel(
            name='CommunityNotificationsGood',
        ),
        migrations.DeleteModel(
            name='CommunityNotificationsMusic',
        ),
        migrations.DeleteModel(
            name='CommunityNotificationsPhoto',
        ),
        migrations.DeleteModel(
            name='CommunityNotificationsPost',
        ),
        migrations.DeleteModel(
            name='CommunityNotificationsVideo',
        ),
        migrations.DeleteModel(
            name='CommunityPrivateGood',
        ),
        migrations.DeleteModel(
            name='CommunityPrivateMusic',
        ),
        migrations.DeleteModel(
            name='CommunityPrivatePhoto',
        ),
        migrations.DeleteModel(
            name='CommunityPrivatePost',
        ),
        migrations.DeleteModel(
            name='CommunityPrivateVideo',
        ),
        migrations.DeleteModel(
            name='CommunitySectionsOpen',
        ),
    ]
