# Generated by Django 3.2 on 2021-04-23 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_alter_photo_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='type',
            field=models.CharField(choices=[('MAI', 'Основной'), ('LIS', 'Пользовательский'), ('PRI', 'Приватный'), ('MAN', 'Созданный персоналом'), ('PRO', 'Обработка'), ('DEL', 'Удалённый'), ('DELP', 'Удалённый приватный'), ('DELM', 'Удалённый менеджерский'), ('CLO', 'Закрытый менеджером'), ('CLOP', 'Закрытый приватный'), ('CLOM', 'Закрытый основной'), ('CLOMA', 'Закрытый менеджерский')], default='PRO', max_length=5, verbose_name='Тип альбома'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='status',
            field=models.CharField(choices=[('PRO', 'Обработка'), ('PUB', 'Опубликовано'), ('DEL', 'Удалено'), ('PRI', 'Приватно'), ('CLO', 'Закрыто модератором'), ('MAN', 'Созданный персоналом'), ('DELP', 'Удалённый приватный'), ('DELM', 'Удалённый менеджерский'), ('CLOP', 'Закрытый приватный'), ('CLOM', 'Закрытый менеджерский')], default='PRO', max_length=5, verbose_name='Тип изображения'),
        ),
    ]
