# Generated by Django 3.2 on 2021-05-13 18:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('communities', '0001_initial'),
        ('gallery', '0004_auto_20210510_1710'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='communities',
            field=models.ManyToManyField(blank=True, related_name='_gallery_album_communities_+', to='communities.Community'),
        ),
        migrations.AddField(
            model_name='album',
            name='community',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='photo_lists_community', to='communities.community', verbose_name='Сообщество'),
        ),
        migrations.AddField(
            model_name='photo',
            name='community',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='photo_community', to='communities.community', verbose_name='Сообщество'),
        ),
        migrations.AlterField(
            model_name='album',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='_gallery_album_users_+', to=settings.AUTH_USER_MODEL),
        ),
    ]
