# Generated by Django 3.2 on 2021-05-16 20:07

from django.conf import settings
import django.contrib.postgres.indexes
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('communities', '0002_communityfollow'),
        ('gallery', '0005_auto_20210513_1823'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhotoList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, verbose_name='uuid')),
                ('name', models.CharField(max_length=250, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('type', models.CharField(choices=[('MAI', 'Основной'), ('LIS', 'Пользовательский'), ('PRI', 'Приватный'), ('MAN', 'Созданный персоналом'), ('_PRO', 'Обработка'), ('_DEL', 'Удалённый'), ('_DELP', 'Удалённый приватный'), ('_DELM', 'Удалённый менеджерский'), ('_CLO', 'Закрытый менеджером'), ('_CLOP', 'Закрытый приватный'), ('_CLOM', 'Закрытый основной'), ('_CLOMA', 'Закрытый менеджерский')], default='_PRO', max_length=6, verbose_name='Тип альбома')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('order', models.PositiveIntegerField(default=0)),
                ('communities', models.ManyToManyField(blank=True, related_name='_gallery_photolist_communities_+', to='communities.Community')),
                ('community', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='photo_lists_community', to='communities.community', verbose_name='Сообщество')),
            ],
            options={
                'verbose_name': 'Фотоальбом',
                'verbose_name_plural': 'Фотоальбомы',
            },
        ),
        migrations.RemoveField(
            model_name='photo',
            name='album',
        ),
        migrations.DeleteModel(
            name='Album',
        ),
        migrations.AddField(
            model_name='photolist',
            name='cover_photo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='gallery.photo', verbose_name='Обожка'),
        ),
        migrations.AddField(
            model_name='photolist',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photo_list_creator', to=settings.AUTH_USER_MODEL, verbose_name='Создатель'),
        ),
        migrations.AddField(
            model_name='photolist',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='_gallery_photolist_users_+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='photo',
            name='list',
            field=models.ManyToManyField(blank=True, related_name='photo_list', to='gallery.PhotoList'),
        ),
        migrations.AddIndex(
            model_name='photolist',
            index=django.contrib.postgres.indexes.BrinIndex(fields=['created'], name='gallery_pho_created_c7a26c_brin'),
        ),
    ]
