# Generated by Django 3.2 on 2021-05-22 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0007_alter_photo_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='status',
            new_name='type',
        ),
    ]
