# Generated by Django 3.2.5 on 2021-10-02 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0008_medialist'),
        ('gallery', '0010_alter_photolist_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='media_list',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='lists.medialist', verbose_name='Медиа-список'),
        ),
    ]
