# Generated by Django 3.2.5 on 2021-10-10 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0013_alter_photo_media_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='is_photo',
            field=models.BooleanField(default=True),
        ),
    ]
