# Generated by Django 3.1.5 on 2021-02-25 17:23

from django.conf import settings
import django.contrib.postgres.indexes
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('elect', '0007_auto_20201111_1901'),
        ('blog', '0017_auto_20210225_1723'),
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElectNewComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('modified', models.DateTimeField(auto_now_add=True)),
                ('text', models.TextField(blank=True)),
                ('is_edited', models.BooleanField(default=False, verbose_name='Изменено')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Удаено')),
                ('commenter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Комментатор')),
                ('new', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.electnew')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='elect_new_comment_replies', to='common.electnewcomment', verbose_name='Родительский комментарий')),
            ],
            options={
                'verbose_name': 'комментарий к новости депутата',
                'verbose_name_plural': 'комментарии к новости депутата',
            },
        ),
        migrations.CreateModel(
            name='ElectComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('modified', models.DateTimeField(auto_now_add=True)),
                ('text', models.TextField(blank=True)),
                ('is_edited', models.BooleanField(default=False, verbose_name='Изменено')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Удаено')),
                ('commenter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Комментатор')),
                ('elect', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='elect.elect')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='elect_comment_replies', to='common.electcomment', verbose_name='Родительский комментарий')),
            ],
            options={
                'verbose_name': 'отзыв о депутате',
                'verbose_name_plural': 'отзывы о депутате',
            },
        ),
        migrations.CreateModel(
            name='BlogComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('modified', models.DateTimeField(auto_now_add=True)),
                ('text', models.TextField(blank=True)),
                ('is_edited', models.BooleanField(default=False, verbose_name='Изменено')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Удаено')),
                ('blog', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.blog')),
                ('commenter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Комментатор')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blog_comment_replies', to='common.blogcomment', verbose_name='Родительский комментарий')),
            ],
            options={
                'verbose_name': 'комментарий к статье',
                'verbose_name_plural': 'комментарии к статье',
            },
        ),
        migrations.AddIndex(
            model_name='electnewcomment',
            index=django.contrib.postgres.indexes.BrinIndex(fields=['created'], name='common_elec_created_b47862_brin'),
        ),
        migrations.AddIndex(
            model_name='electcomment',
            index=django.contrib.postgres.indexes.BrinIndex(fields=['created'], name='common_elec_created_d64741_brin'),
        ),
        migrations.AddIndex(
            model_name='blogcomment',
            index=django.contrib.postgres.indexes.BrinIndex(fields=['created'], name='common_blog_created_c802a3_brin'),
        ),
    ]
