# Generated by Django 3.1.5 on 2021-03-20 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_blogcommentdoc_blogcommentphoto_electcommentdoc_electcommentphoto_electnewcommentdoc_electnewcomment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='electcommentdoc',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='electcommentphoto',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='electcommentvotes',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='electcommentvotes',
            name='user',
        ),
        migrations.DeleteModel(
            name='ElectComment',
        ),
        migrations.DeleteModel(
            name='ElectCommentDoc',
        ),
        migrations.DeleteModel(
            name='ElectCommentPhoto',
        ),
        migrations.DeleteModel(
            name='ElectCommentVotes',
        ),
    ]
