# Generated by Django 3.2 on 2021-04-15 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_auto_20210320_1144'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogcommentphoto',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='electnewcommentdoc',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='electnewcommentphoto',
            name='comment',
        ),
        migrations.AlterModelOptions(
            name='blogcomment',
            options={'ordering': ['-created'], 'verbose_name': 'комментарий к статье', 'verbose_name_plural': 'комментарии к статье'},
        ),
        migrations.AlterModelOptions(
            name='electnewcomment',
            options={'ordering': ['-created'], 'verbose_name': 'комментарий к новости депутата', 'verbose_name_plural': 'комментарии к новости депутата'},
        ),
        migrations.RemoveField(
            model_name='blogcomment',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='blogcomment',
            name='is_edited',
        ),
        migrations.RemoveField(
            model_name='blogcomment',
            name='modified',
        ),
        migrations.RemoveField(
            model_name='electnewcomment',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='electnewcomment',
            name='is_edited',
        ),
        migrations.RemoveField(
            model_name='electnewcomment',
            name='modified',
        ),
        migrations.AddField(
            model_name='blogcomment',
            name='attach',
            field=models.CharField(blank=True, max_length=200, verbose_name='Прикрепленные элементы'),
        ),
        migrations.AddField(
            model_name='blogcomment',
            name='status',
            field=models.CharField(choices=[('DEL', 'Удалённый'), ('EDI', 'Изменённый'), ('CLO', 'Закрытый менеджером'), ('PRO', 'Обработка'), ('PUB', 'Опубликовано')], default='PRO', max_length=5, verbose_name='Тип альбома'),
        ),
        migrations.AddField(
            model_name='electnewcomment',
            name='attach',
            field=models.CharField(blank=True, max_length=200, verbose_name='Прикрепленные элементы'),
        ),
        migrations.AddField(
            model_name='electnewcomment',
            name='status',
            field=models.CharField(choices=[('DEL', 'Удалённый'), ('EDI', 'Изменённый'), ('CLO', 'Закрытый менеджером'), ('PRO', 'Обработка'), ('PUB', 'Опубликовано')], default='PRO', max_length=5, verbose_name='Тип альбома'),
        ),
        migrations.AlterField(
            model_name='blogcomment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blog_comment_replies', to='common.blogcomment', verbose_name='Родительский комментарий'),
        ),
        migrations.AlterField(
            model_name='blogcommentvotes',
            name='vote',
            field=models.IntegerField(choices=[(1, 'Нравится')], verbose_name='Голос'),
        ),
        migrations.AlterField(
            model_name='blogvotes',
            name='vote',
            field=models.CharField(choices=[('DIS', 'Не оценил'), ('LIK', 'Оценил'), ('INE', 'Объект инертный')], max_length=5, verbose_name='Голос'),
        ),
        migrations.AlterField(
            model_name='electnewcomment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='elect_new_comment_replies', to='common.electnewcomment', verbose_name='Родительский комментарий'),
        ),
        migrations.AlterField(
            model_name='electnewcommentvotes',
            name='vote',
            field=models.IntegerField(choices=[(1, 'Нравится')], default=0, verbose_name='Голос'),
        ),
        migrations.AlterField(
            model_name='electnewvotes2',
            name='vote',
            field=models.CharField(choices=[('DIS', 'Не оценил'), ('LIK', 'Оценил'), ('INE', 'Объект инертный')], max_length=5, verbose_name='Голос'),
        ),
        migrations.DeleteModel(
            name='BlogCommentDoc',
        ),
        migrations.DeleteModel(
            name='BlogCommentPhoto',
        ),
        migrations.DeleteModel(
            name='ElectNewCommentDoc',
        ),
        migrations.DeleteModel(
            name='ElectNewCommentPhoto',
        ),
    ]
