# Generated by Django 3.2 on 2021-05-10 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0006_auto_20210415_1935'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogcomment',
            name='like',
            field=models.PositiveIntegerField(default=0, verbose_name='Кол-во лайков'),
        ),
        migrations.AddField(
            model_name='electnewcomment',
            name='like',
            field=models.PositiveIntegerField(default=0, verbose_name='Кол-во лайков'),
        ),
        migrations.AlterField(
            model_name='blogcomment',
            name='status',
            field=models.CharField(choices=[('PUB', 'Опубликовано'), ('EDI', 'Изменённый'), ('_PRO', 'Обработка'), ('_DEL', 'Удалённый'), ('_DEL', 'Удалённый изменённый'), ('_CLO', 'Закрытый менеджером'), ('_CLO', 'Закрытый изменённый')], default='_PRO', max_length=5, verbose_name='Тип комментария'),
        ),
        migrations.AlterField(
            model_name='electnewcomment',
            name='status',
            field=models.CharField(choices=[('PUB', 'Опубликовано'), ('EDI', 'Изменённый'), ('_PRO', 'Обработка'), ('_DEL', 'Удалённый'), ('_DEL', 'Удалённый изменённый'), ('_CLO', 'Закрытый менеджером'), ('_CLO', 'Закрытый изменённый')], default='_PRO', max_length=5, verbose_name='Тип комментария'),
        ),
    ]
