# Generated by Django 3.2 on 2021-05-22 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0007_auto_20210510_1710'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogcomment',
            old_name='status',
            new_name='type',
        ),
        migrations.RenameField(
            model_name='electnewcomment',
            old_name='status',
            new_name='type',
        ),
    ]
