# Generated by Django 3.2 on 2021-07-11 18:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('elect', '0009_auto_20210523_1712'),
        ('common', '0008_auto_20210522_1928'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElectVotes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote', models.CharField(choices=[('DIS', 'Не оценил'), ('LIK', 'Оценил'), ('INE', 'Объект инертный')], max_length=5, verbose_name='Голос')),
                ('elect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elect.elect')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
    ]
