# Generated by Django 3.2.5 on 2021-08-11 16:10

from django.conf import settings
import django.contrib.postgres.indexes
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0004_auto_20210811_1610'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organizations', '0002_organization_description'),
        ('common', '0009_electvotes'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationCommentVotes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote', models.IntegerField(choices=[(1, 'Нравится')], verbose_name='Голос')),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.blogcomment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
        migrations.CreateModel(
            name='OrganizationComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('text', models.TextField(blank=True)),
                ('attach', models.CharField(blank=True, max_length=200, verbose_name='Прикрепленные элементы')),
                ('type', models.CharField(choices=[('PUB', 'Опубликовано'), ('EDI', 'Изменённый'), ('_PRO', 'Обработка'), ('_DEL', 'Удалённый'), ('_DEL', 'Удалённый изменённый'), ('_CLO', 'Закрытый менеджером'), ('_CLO', 'Закрытый изменённый')], default='_PRO', max_length=5, verbose_name='Тип комментария')),
                ('like', models.PositiveIntegerField(default=0, verbose_name='Кол-во лайков')),
                ('commenter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Комментатор')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organizations.organization')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organization_comment_replies', to='common.organizationcomment', verbose_name='Родительский комментарий')),
            ],
            options={
                'verbose_name': 'комментарий к организации',
                'verbose_name_plural': 'комментарии к организации',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='CommunityVotes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote', models.CharField(choices=[('DIS', 'Не оценил'), ('LIK', 'Оценил'), ('INE', 'Объект инертный')], max_length=5, verbose_name='Голос')),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='communities.community')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
        migrations.AddIndex(
            model_name='organizationcomment',
            index=django.contrib.postgres.indexes.BrinIndex(fields=['created'], name='common_orga_created_c2ff06_brin'),
        ),
    ]
