# Generated by Django 3.2.5 on 2021-08-13 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0010_auto_20210811_1610'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecoveryPhoneCodes',
            fields=[
                ('phone', models.CharField(max_length=15, verbose_name='Телефон')),
                ('code', models.PositiveSmallIntegerField(default=0, verbose_name='Код')),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
        ),
    ]
