# Generated by Django 3.2.5 on 2021-09-07 19:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('elect', '0018_elect_is_new'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('common', '0011_recoveryphonecodes'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElectRating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vakcine', models.SmallIntegerField(choices=[(-5, '#F8696B'), (-4, '#F98370'), (-3, '#FA9D75'), (-2, '#FCB77A'), (-1, '#FDD17F'), (0, '#FFEB84'), (1, '#E0E383'), (2, '#C1DA81'), (3, '#A2D07F'), (4, '#83C77D'), (5, '#63BE7B')], verbose_name='Добровольность вакцинации')),
                ('pp_825', models.SmallIntegerField(choices=[(-5, '#F8696B'), (-4, '#F98370'), (-3, '#FA9D75'), (-2, '#FCB77A'), (-1, '#FDD17F'), (0, '#FFEB84'), (1, '#E0E383'), (2, '#C1DA81'), (3, '#A2D07F'), (4, '#83C77D'), (5, '#63BE7B')], verbose_name='Отмена пп 825')),
                ('safe_family', models.SmallIntegerField(choices=[(-5, '#F8696B'), (-4, '#F98370'), (-3, '#FA9D75'), (-2, '#FCB77A'), (-1, '#FDD17F'), (0, '#FFEB84'), (1, '#E0E383'), (2, '#C1DA81'), (3, '#A2D07F'), (4, '#83C77D'), (5, '#63BE7B')], verbose_name='Защита прав семьи')),
                ('pro_life', models.SmallIntegerField(choices=[(-5, '#F8696B'), (-4, '#F98370'), (-3, '#FA9D75'), (-2, '#FCB77A'), (-1, '#FDD17F'), (0, '#FFEB84'), (1, '#E0E383'), (2, '#C1DA81'), (3, '#A2D07F'), (4, '#83C77D'), (5, '#63BE7B')], verbose_name='Защита жизни с момента зачатия')),
                ('free_vacation', models.SmallIntegerField(choices=[(-5, '#F8696B'), (-4, '#F98370'), (-3, '#FA9D75'), (-2, '#FCB77A'), (-1, '#FDD17F'), (0, '#FFEB84'), (1, '#E0E383'), (2, '#C1DA81'), (3, '#A2D07F'), (4, '#83C77D'), (5, '#63BE7B')], verbose_name='Свобода образования')),
                ('elect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elect.elect')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
    ]
