# Generated by Django 3.2.5 on 2021-09-25 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0014_auto_20210910_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electrating',
            name='pp_825',
            field=models.SmallIntegerField(choices=[(-3, '#FA9D75'), (-2, '#FCB77A'), (-1, '#FDD17F'), (0, '#FFEB84'), (1, '#E0E383'), (2, '#C1DA81'), (3, '#A2D07F')], default=0, verbose_name='Отмена обязательной вакцинации по приказу минздрава 825'),
        ),
    ]
