# Generated by Django 3.2.5 on 2021-11-18 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0015_alter_electrating_pp_825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogcomment',
            name='text',
            field=models.TextField(blank=True, max_length=3000),
        ),
    ]
