# Generated by Django 3.2.5 on 2021-12-29 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0018_smilecategory_smiles_stickercategory_stickers_userpopulatesmiles_userpopulatestickers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smiles',
            name='image',
            field=models.FileField(upload_to='smiles/'),
        ),
        migrations.AlterField(
            model_name='stickers',
            name='image',
            field=models.FileField(upload_to='stickers/'),
        ),
    ]
