# Generated by Django 3.2.5 on 2022-01-09 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0021_auto_20220109_1232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smiles',
            name='name',
            field=models.CharField(max_length=32, verbose_name='Название'),
        ),
    ]
