# Generated by Django 3.2.5 on 2022-01-09 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0022_alter_smiles_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smilecategory',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='smiles',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='stickercategory',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='stickers',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Название'),
        ),
    ]
