# Generated by Django 3.2.5 on 2022-01-10 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0023_auto_20220109_1724'),
    ]

    operations = [
        migrations.AddField(
            model_name='smilecategory',
            name='preview',
            field=models.FileField(blank=True, upload_to='smiles_preview/'),
        ),
        migrations.AddField(
            model_name='stickercategory',
            name='preview',
            field=models.FileField(blank=True, upload_to='stickers_preview/'),
        ),
    ]
