# Generated by Django 3.2.11 on 2022-02-06 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0024_auto_20220110_1128'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogvotes',
            name='blog',
        ),
        migrations.RemoveField(
            model_name='blogvotes',
            name='user',
        ),
        migrations.RemoveField(
            model_name='communityvotes',
            name='community',
        ),
        migrations.RemoveField(
            model_name='communityvotes',
            name='user',
        ),
        migrations.RemoveField(
            model_name='electnewcommentvotes',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='electnewcommentvotes',
            name='user',
        ),
        migrations.RemoveField(
            model_name='electnewvotes2',
            name='new',
        ),
        migrations.RemoveField(
            model_name='electnewvotes2',
            name='user',
        ),
        migrations.RemoveField(
            model_name='electrating',
            name='elect',
        ),
        migrations.RemoveField(
            model_name='electrating',
            name='user',
        ),
        migrations.RemoveField(
            model_name='electvotes',
            name='elect',
        ),
        migrations.RemoveField(
            model_name='electvotes',
            name='user',
        ),
        migrations.RemoveField(
            model_name='organizationcommentvotes',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='organizationcommentvotes',
            name='user',
        ),
        migrations.DeleteModel(
            name='BlogCommentVotes',
        ),
        migrations.DeleteModel(
            name='BlogVotes',
        ),
        migrations.DeleteModel(
            name='CommunityVotes',
        ),
        migrations.DeleteModel(
            name='ElectNewCommentVotes',
        ),
        migrations.DeleteModel(
            name='ElectNewVotes2',
        ),
        migrations.DeleteModel(
            name='ElectRating',
        ),
        migrations.DeleteModel(
            name='ElectVotes',
        ),
        migrations.DeleteModel(
            name='OrganizationCommentVotes',
        ),
    ]
