# Generated by Django 3.2 on 2021-05-25 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moderationpenalty',
            name='expiration',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Окончание'),
        ),
    ]
