# Generated by Django 3.2 on 2021-05-26 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managers', '0002_alter_moderationpenalty_expiration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moderated',
            name='type',
            field=models.CharField(choices=[('USE', 'Пользователь'), ('COM', 'Сообщество'), ('MUL', 'Плейлист'), ('MUS', 'Трек'), ('SUL', 'Список опросов'), ('SUR', 'Опрос'), ('ELE', 'Активность депутата'), ('ELEC', 'Коммент к активности депутата'), ('DOL', 'Список документов'), ('DOC', 'документ'), ('PHL', 'Список фотографий'), ('PHO', 'Фотография'), ('PHOC', 'Коммент к фотографии'), ('VIL', 'Список роликов'), ('VID', 'Ролик'), ('VIDC', 'Коммент к ролику')], max_length=5, verbose_name='Класс объекта'),
        ),
        migrations.AlterField(
            model_name='moderationpenalty',
            name='status',
            field=models.CharField(choices=[('S', 'Приостановлено'), ('C', 'Закрыто'), ('BA', 'Вывешен баннер')], max_length=5, verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='moderationpenalty',
            name='type',
            field=models.CharField(choices=[('USE', 'Пользователь'), ('COM', 'Сообщество'), ('MUL', 'Плейлист'), ('MUS', 'Трек'), ('SUL', 'Список опросов'), ('SUR', 'Опрос'), ('ELE', 'Активность депутата'), ('ELEC', 'Коммент к активности депутата'), ('DOL', 'Список документов'), ('DOC', 'документ'), ('PHL', 'Список фотографий'), ('PHO', 'Фотография'), ('PHOC', 'Коммент к фотографии'), ('VIL', 'Список роликов'), ('VID', 'Ролик'), ('VIDC', 'Коммент к ролику')], max_length=5, verbose_name='Класс объекта'),
        ),
    ]
