# Generated by Django 3.2 on 2021-06-09 17:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('managers', '0003_auto_20210526_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moderated',
            name='type',
            field=models.CharField(choices=[('USE', 'Пользователь'), ('COM', 'Сообщество'), ('MUL', 'Плейлист'), ('MUS', 'Трек'), ('SUL', 'Список опросов'), ('SUR', 'Опрос'), ('ELE', 'Активность депутата'), ('ELEC', 'Коммент к активности депутата'), ('BLO', 'Блог'), ('BLOC', 'Коммент к блогу'), ('DOL', 'Список документов'), ('DOC', 'документ'), ('PHL', 'Список фотографий'), ('PHO', 'Фотография'), ('PHOC', 'Коммент к фотографии'), ('VIL', 'Список роликов'), ('VID', 'Ролик'), ('VIDC', 'Коммент к ролику')], max_length=5, verbose_name='Класс объекта'),
        ),
        migrations.AlterField(
            model_name='moderationpenalty',
            name='type',
            field=models.CharField(choices=[('USE', 'Пользователь'), ('COM', 'Сообщество'), ('MUL', 'Плейлист'), ('MUS', 'Трек'), ('SUL', 'Список опросов'), ('SUR', 'Опрос'), ('ELE', 'Активность депутата'), ('ELEC', 'Коммент к активности депутата'), ('BLO', 'Блог'), ('BLOC', 'Коммент к блогу'), ('DOL', 'Список документов'), ('DOC', 'документ'), ('PHL', 'Список фотографий'), ('PHO', 'Фотография'), ('PHOC', 'Коммент к фотографии'), ('VIL', 'Список роликов'), ('VID', 'Ролик'), ('VIDC', 'Коммент к ролику')], max_length=5, verbose_name='Класс объекта'),
        ),
        migrations.CreateModel(
            name='CanWorkStaffBlogUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_work_administrator', models.BooleanField(default=False, verbose_name='Может добавлять администраторов блога')),
                ('can_work_moderator', models.BooleanField(default=False, verbose_name='Может добавлять модераторов блога')),
                ('can_work_editor', models.BooleanField(default=False, verbose_name='Может добавлять редакторов блога')),
                ('can_work_advertiser', models.BooleanField(default=False, verbose_name='Может добавлять рекламодателей блога')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='can_work_staff_blog_user', to=settings.AUTH_USER_MODEL, verbose_name='Создатель персонала в товарах')),
            ],
            options={
                'verbose_name': 'Создатель персонала блога',
                'verbose_name_plural': 'Создатели персонала блога',
            },
        ),
        migrations.CreateModel(
            name='BlogUserStaff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(blank=True, choices=[('A', 'Администратор'), ('M', 'Модератор'), ('E', 'Редактор'), ('R', 'Рекламодатель')], max_length=5, verbose_name='Уровень доступа')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='blog_user_staff', to=settings.AUTH_USER_MODEL, verbose_name='Особый пользователь')),
            ],
            options={
                'verbose_name': 'Полномочия в блоге',
                'verbose_name_plural': 'Полномочия в блоге',
            },
        ),
    ]
