# Generated by Django 3.2.5 on 2021-11-26 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managers', '0005_auto_20210811_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moderated',
            name='status',
            field=models.CharField(choices=[('P', 'На рассмотрении'), ('S', 'Объект заморожен'), ('C', 'Объект закрыт'), ('BG', 'Объекту присвоен баннер'), ('R', 'Жалобы удалены'), ('SR', 'Предложенный элемент не прошел проверку')], default='P', max_length=5, verbose_name='Статус'),
        ),
    ]
