# Generated by Django 3.2.5 on 2021-08-06 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True
    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядковый номер')),
                ('image', models.ImageField(blank=True, upload_to='organizations/')),
                ('email_1', models.EmailField(blank=True, max_length=254, verbose_name='Почта 1')),
                ('email_2', models.EmailField(blank=True, max_length=254, verbose_name='Почта 2')),
                ('phone_1', models.CharField(blank=True, max_length=17, verbose_name='Телефон 1')),
                ('phone_2', models.CharField(blank=True, max_length=17, verbose_name='Телефон 2')),
                ('address_1', models.CharField(blank=True, max_length=100, verbose_name='Адрес 1')),
                ('address_2', models.CharField(blank=True, max_length=100, verbose_name='Адрес 2')),
                ('type', models.PositiveSmallIntegerField(choices=[(1, 'Автомобильный бизнес'), (2, 'Административный персонал'), (3, 'Банки, инвестиции, лизинг'), (4, 'Безопасность'), (5, 'Бухгалтерия, управленческий учет, финансы предприятия'), (6, 'Высший менеджмент'), (7, 'Государственная служба, некоммерческие организации'), (8, 'Добыча сырья'), (9, 'Домашний персонал'), (10, 'Закупки'), (11, 'Инсталляция и сервис'), (12, 'Информационные технологии, интернет, телеком'), (13, 'Искусство, развлечения, масс-медиа'), (14, 'Консультирование'), (15, 'Маркетинг, реклама, PR'), (16, 'Медицина, фармацевтика'), (17, 'Наука, образование'), (18, 'Начало карьеры, студенты'), (19.0, 'Продажи'), (20, 'Производство, сельское хозяйство'), (21, 'Рабочий персонал'), (22, 'Спортивные клубы, фитнес, салоны красоты'), (23, 'Страхование'), (24, 'Строительство, недвижимость'), (25, 'Транспорт, логистика'), (26, 'Туризм, гостиницы, рестораны'), (27, 'Управление персоналом, тренинги'), (28, 'Юристы')], default=1, verbose_name='Тип деятельности')),
               
            ],
            options={
                'verbose_name': 'Организация',
                'verbose_name_plural': 'Организации',
                'ordering': ['order', 'name'],
            },
        ),
    ]
