# Generated by Django 3.2 on 2021-04-22 11:24

from django.db import migrations, models
import docs.helpers


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doc',
            name='file',
            field=models.FileField(upload_to=docs.helpers.upload_to_doc_directory, validators=[docs.helpers.validate_file_extension], verbose_name='Документ'),
        ),
    ]
