# Generated by Django 2.2.16 on 2020-10-27 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='elects',
            field=models.ManyToManyField(blank=True, related_name='elect_news', to='elect.Elect', verbose_name='Чиновник'),
        ),
    ]
