# Generated by Django 2.2.16 on 2020-11-11 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0002_auto_20201026_1413'),
        ('blog', '0004_auto_20201111_1407'),
    ]

    operations = [
        migrations.RenameField(
            model_name='electdoc',
            old_name='post',
            new_name='new',
        ),
        migrations.RenameField(
            model_name='electphoto',
            old_name='post',
            new_name='new',
        ),
        migrations.RemoveField(
            model_name='electnew',
            name='category',
        ),
        migrations.AddField(
            model_name='electnew',
            name='category',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, related_name='elect_cat', to='lists.BlogCategory', verbose_name='Категория записи чиновника'),
            preserve_default=False,
        ),
    ]
