# Generated by Django 2.2.16 on 2020-11-11 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elect', '0006_auto_20201104_1657'),
        ('blog', '0005_auto_20201111_1423'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='electnew',
            name='elect',
        ),
        migrations.AddField(
            model_name='electnew',
            name='elect',
            field=models.ManyToManyField(blank=True, related_name='new_elect', to='elect.Elect', verbose_name='Чиновник'),
        ),
    ]
