# Generated by Django 2.2.16 on 2020-11-12 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('elect', '0007_auto_20201111_1901'),
        ('blog', '0006_auto_20201111_1454'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='electnew',
            name='elect',
        ),
        migrations.AddField(
            model_name='electnew',
            name='elect',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, related_name='new_elect', to='elect.Elect', verbose_name='Чиновник'),
            preserve_default=False,
        ),
    ]
