# Generated by Django 2.2.16 on 2020-11-12 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20201112_1236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electnew',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='elect_cat', to='lists.BlogCategory', verbose_name='Категория записи чиновника'),
        ),
    ]
