# Generated by Django 2.2.16 on 2020-11-28 15:41

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20201127_1923'),
    ]

    operations = [
        migrations.AddField(
            model_name='electnew',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='electnew',
            name='status',
            field=models.CharField(choices=[('D', 'На рассмотрении'), ('PG', 'Обработка'), ('P', 'Опубликовано')], default='P', max_length=2, verbose_name='Статус записи'),
        ),
    ]
