# Generated by Django 2.2.16 on 2020-11-29 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20201128_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electdoc',
            name='new',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='doc_new', to='blog.ElectNew'),
        ),
        migrations.AlterField(
            model_name='electphoto',
            name='new',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='image_new', to='blog.ElectNew'),
        ),
    ]
