# Generated by Django 2.2.16 on 2020-11-29 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20201129_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electnew',
            name='content',
            field=models.TextField(verbose_name='Текс'),
        ),
    ]
