# Generated by Django 3.1.5 on 2021-02-25 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_auto_20210218_1534'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogcommentvotes',
            name='blog',
        ),
        migrations.RemoveField(
            model_name='blogcommentvotes',
            name='user',
        ),
        migrations.RemoveField(
            model_name='blogvotes',
            name='blog',
        ),
        migrations.RemoveField(
            model_name='blogvotes',
            name='user',
        ),
        migrations.RemoveField(
            model_name='electcommentvotes',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='electcommentvotes',
            name='user',
        ),
        migrations.RemoveField(
            model_name='electnewcomment',
            name='commenter',
        ),
        migrations.RemoveField(
            model_name='electnewcomment',
            name='new',
        ),
        migrations.RemoveField(
            model_name='electnewcomment',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='electvotes',
            name='new',
        ),
        migrations.RemoveField(
            model_name='electvotes',
            name='user',
        ),
        migrations.DeleteModel(
            name='BlogComment',
        ),
        migrations.DeleteModel(
            name='BlogCommentVotes',
        ),
        migrations.DeleteModel(
            name='BlogVotes',
        ),
        migrations.DeleteModel(
            name='ElectCommentVotes',
        ),
        migrations.DeleteModel(
            name='ElectNewComment',
        ),
        migrations.DeleteModel(
            name='ElectVotes',
        ),
    ]
