# Generated by Django 3.1.5 on 2021-03-20 16:46

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0002_auto_20201026_1413'),
        ('blog', '0017_auto_20210225_1723'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='electnew',
            options={'ordering': ['-created'], 'verbose_name': 'Активность', 'verbose_name_plural': 'Лента чиновника'},
        ),
        migrations.RemoveField(
            model_name='blog',
            name='elects',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='tags',
        ),
        migrations.AddField(
            model_name='electnew',
            name='comments_enabled',
            field=models.BooleanField(default=True, verbose_name='Разрешить комментарии'),
        ),
        migrations.AddField(
            model_name='electnew',
            name='votes_on',
            field=models.BooleanField(default=True, verbose_name='Реакции разрешены'),
        ),
        migrations.AlterField(
            model_name='electnew',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='elect_cat', to='lists.electnewscategory', verbose_name='Категория активности'),
        ),
        migrations.AlterField(
            model_name='electnew',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
        migrations.AlterField(
            model_name='electnew',
            name='status',
            field=models.CharField(choices=[('D', 'Черновик'), ('PG', 'Обработка'), ('P', 'Опубликовано')], default='P', max_length=2, verbose_name='Статус записи'),
        ),
    ]
