# Generated by Django 3.2 on 2021-05-10 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_auto_20210415_1935'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='tags',
        ),
        migrations.AddField(
            model_name='blog',
            name='comment',
            field=models.PositiveIntegerField(default=0, verbose_name='Кол-во комментов'),
        ),
        migrations.AddField(
            model_name='blog',
            name='dislike',
            field=models.PositiveIntegerField(default=0, verbose_name='Кол-во дизлайков'),
        ),
        migrations.AddField(
            model_name='blog',
            name='inert',
            field=models.PositiveIntegerField(default=0, verbose_name='Кол-во inert'),
        ),
        migrations.AddField(
            model_name='blog',
            name='like',
            field=models.PositiveIntegerField(default=0, verbose_name='Кол-во лайков'),
        ),
        migrations.AddField(
            model_name='blog',
            name='view',
            field=models.PositiveIntegerField(default=0, verbose_name='Кол-во просмотров'),
        ),
        migrations.AddField(
            model_name='electnew',
            name='comment',
            field=models.PositiveIntegerField(default=0, verbose_name='Кол-во комментов'),
        ),
        migrations.AddField(
            model_name='electnew',
            name='dislike',
            field=models.PositiveIntegerField(default=0, verbose_name='Кол-во дизлайков'),
        ),
        migrations.AddField(
            model_name='electnew',
            name='inert',
            field=models.PositiveIntegerField(default=0, verbose_name='Кол-во inert'),
        ),
        migrations.AddField(
            model_name='electnew',
            name='like',
            field=models.PositiveIntegerField(default=0, verbose_name='Кол-во лайков'),
        ),
        migrations.AddField(
            model_name='electnew',
            name='view',
            field=models.PositiveIntegerField(default=0, verbose_name='Кол-во просмотров'),
        ),
        migrations.AlterField(
            model_name='electnew',
            name='status',
            field=models.CharField(choices=[('_DRA', 'Черновик'), ('_PRO', 'В процессе'), ('PUB', 'Опубликованый'), ('_DEL', 'Удаленый'), ('_CLO', 'Закрытый'), ('MAN', 'Менеджерский'), ('_SUG', 'Предложенный')], default='_PRO', max_length=5, verbose_name='Статус записи'),
        ),
    ]
