# Generated by Django 3.2 on 2021-05-12 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_auto_20210510_1710'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='repost',
            field=models.PositiveIntegerField(default=0, verbose_name='Кол-во репостов'),
        ),
        migrations.AddField(
            model_name='electnew',
            name='repost',
            field=models.PositiveIntegerField(default=0, verbose_name='Кол-во репостов'),
        ),
    ]
