# Generated by Django 3.2 on 2021-05-23 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0023_rename_status_electnew_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electnew',
            name='type',
            field=models.CharField(choices=[('_PRO', 'Обработка'), ('PUB', 'Опубликовано'), ('_DEL', 'Удалено'), ('_CLO', 'Закрыто модератором'), ('MAN', 'Созданный персоналом'), ('_DELM', 'Удалённый менеджерский'), ('_CLOM', 'Закрытый менеджерский')], default='_PRO', max_length=5, verbose_name='Статус записи'),
        ),
    ]
