# Generated by Django 3.2 on 2021-05-23 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0024_alter_electnew_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electnew',
            name='description',
            field=models.TextField(blank=True, max_length=1000, verbose_name='Описание'),
        ),
    ]
