# Generated by Django 3.2 on 2021-05-23 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0025_alter_electnew_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='electnew',
            name='attach',
            field=models.CharField(blank=True, max_length=200, verbose_name='Прикрепленные элементы'),
        ),
        migrations.AlterField(
            model_name='electnew',
            name='type',
            field=models.CharField(choices=[('_PRO', 'Обработка'), ('_PRO', 'Предложенный'), ('PUB', 'Опубликовано'), ('_DEL', 'Удалено'), ('_CLO', 'Закрыто модератором'), ('MAN', 'Созданный персоналом'), ('_DELM', 'Удалённый менеджерский'), ('_CLOM', 'Закрытый менеджерский')], default='_PRO', max_length=5, verbose_name='Статус записи'),
        ),
    ]
