# Generated by Django 3.2 on 2021-05-23 11:58

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0027_alter_electnew_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='electnew',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(blank=True, upload_to='blog/%Y/%m/%d/', verbose_name='Главное изображение'),
        ),
    ]
