# Generated by Django 3.2 on 2021-05-25 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0028_electnew_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electnew',
            name='type',
            field=models.CharField(choices=[('_PRO', 'обрабатывается'), ('_SUG', 'на рассмотрении'), ('PUB', 'опубликована'), ('_DEL', 'удалена'), ('_CLO', 'закрыта модератором'), ('MAN', 'создана персоналом'), ('_DELM', 'удалена менеджерский'), ('_CLOM', 'закрыта менеджерский'), ('_REJ', 'отклонена модератором')], default='_PRO', max_length=5, verbose_name='Статус записи'),
        ),
    ]
