# Generated by Django 3.2 on 2021-06-10 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0030_alter_electnew_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electnew',
            name='type',
            field=models.CharField(choices=[('_PRO', 'обрабатывается'), ('SUG', 'на рассмотрении'), ('PUB', 'опубликована'), ('_DEL', 'удалена'), ('_CLO', 'закрыта модератором'), ('MAN', 'создана персоналом'), ('_DELS', 'удалена предложенная'), ('_CLOS', 'предложенная менеджерский'), ('_DELM', 'удалена менеджерский'), ('_CLOM', 'закрыта менеджерский'), ('_REJ', 'отклонена модератором')], default='_PRO', max_length=5, verbose_name='Статус записи'),
        ),
    ]
