# Generated by Django 3.2 on 2021-07-13 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('elect', '0009_auto_20210523_1712'),
        ('blog', '0032_alter_electnew_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electnew',
            name='elect',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='new_elect', to='elect.elect', verbose_name='Чиновник'),
        ),
    ]
