# Generated by Django 3.2.5 on 2021-07-27 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0033_alter_electnew_elect'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='type',
            field=models.CharField(choices=[('PUB', 'опубликована'), ('_DEL', 'удалена')], default='PUB', max_length=5, verbose_name='Статус записи'),
        ),
    ]
