# Generated by Django 3.2.5 on 2021-08-30 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0005_remove_managertag_new'),
        ('blog', '0035_auto_20210812_1753'),
    ]

    operations = [
        migrations.AddField(
            model_name='electnew',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='elect_list', to='tags.ManagerTag', verbose_name='Орган гос. власти'),
        ),
    ]
