# Generated by Django 3.2.5 on 2021-08-31 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0006_remove_managertag_blog'),
        ('blog', '0036_electnew_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='_blog_blog_tags_+', to='tags.ManagerTag', verbose_name='Теги'),
        ),
        migrations.AlterField(
            model_name='electnew',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='_blog_electnew_tags_+', to='tags.ManagerTag', verbose_name='Теги'),
        ),
    ]
