# Generated by Django 3.2.5 on 2021-10-24 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0037_auto_20210831_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electnew',
            name='description',
            field=models.TextField(blank=True, max_length=5000, verbose_name='Описание'),
        ),
    ]
