# Generated by Django 3.2.5 on 2021-11-19 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0038_alter_electnew_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='electnew',
            name='is_fixed',
            field=models.BooleanField(default=False, verbose_name='Закреплено'),
        ),
    ]
