# Generated by Django 3.2.5 on 2022-01-12 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('region', '0007_region_is_deleted'),
        ('elect', '0033_elect_type'),
        ('blog', '0039_electnew_is_fixed'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='elect',
            field=models.ManyToManyField(blank=True, related_name='_blog_blog_elect_+', to='elect.Elect', verbose_name='Депутаты'),
        ),
        migrations.AddField(
            model_name='blog',
            name='region',
            field=models.ManyToManyField(blank=True, related_name='_blog_blog_region_+', to='region.Region', verbose_name='Регионы'),
        ),
    ]
