# Generated by Django 3.2.11 on 2022-02-06 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0041_blog_attach'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='description',
            field=models.CharField(blank=True, max_length=6000, verbose_name='Описание'),
        ),
    ]
