# Generated by Django 3.2 on 2021-04-16 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blog', '0019_auto_20210415_1935'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManagerTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('blog', models.ManyToManyField(blank=True, related_name='blog_tags', to='blog.Blog')),
                ('new', models.ManyToManyField(blank=True, related_name='new_tags', to='blog.ElectNew')),
                ('parent', models.ManyToManyField(blank=True, related_name='_tags_managertag_parent_+', to='tags.ManagerTag')),
            ],
            options={
                'verbose_name': 'Наш тег',
                'verbose_name_plural': 'Наши теги',
            },
        ),
    ]
