# Generated by Django 3.2 on 2021-07-03 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='managertag',
            name='parent',
        ),
        migrations.AddField(
            model_name='managertag',
            name='parent',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tags.managertag', verbose_name='Родитель'),
            preserve_default=False,
        ),
    ]
