# Generated by Django 3.2.5 on 2021-08-31 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0005_remove_managertag_new'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='managertag',
            name='blog',
        ),
    ]
