# Generated by Django 3.2.5 on 2021-09-05 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0006_remove_managertag_blog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='managertag',
            options={'ordering': ['name'], 'verbose_name': 'Наш тег', 'verbose_name_plural': 'Наши теги'},
        ),
    ]
