# Generated by Django 3.2.5 on 2021-07-29 12:08

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('region', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(blank=True, upload_to='regions/%Y/%m/%d/', verbose_name='Главное изображение'),
        ),
    ]
