# Generated by Django 3.2.5 on 2021-08-02 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('region', '0002_region_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='region',
            name='svg',
            field=models.CharField(blank=True, max_length=2000, verbose_name='SVG'),
        ),
    ]
