# Generated by Django 3.2.5 on 2021-08-02 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('region', '0003_alter_region_svg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='region',
            name='svg',
            field=models.CharField(blank=True, max_length=2200, verbose_name='SVG'),
        ),
    ]
