# Generated by Django 3.2.5 on 2021-08-02 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('region', '0004_alter_region_svg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='region',
            name='svg',
            field=models.TextField(blank=True, verbose_name='SVG'),
        ),
    ]
