# Generated by Django 3.2.5 on 2021-11-18 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('region', '0006_auto_20210809_1319'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
