# Generated by Django 2.2.16 on 2020-10-19 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Имя')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('message', models.TextField(max_length=500, verbose_name='Сообщение')),
            ],
            options={
                'verbose_name': 'Сообщение с формы связи',
                'verbose_name_plural': 'Сообщения с формы связи',
            },
        ),
    ]
