# Generated by Django 2.2.16 on 2020-11-12 14:22

import django.contrib.postgres.indexes
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogNumbers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.PositiveIntegerField(default=0, verbose_name='Кто смотрит')),
                ('new', models.PositiveIntegerField(default=0, verbose_name='Какую новость проекта смотрит')),
                ('platform', models.PositiveIntegerField(default=0, verbose_name='0 Комп, 1 Телефон')),
                ('created', models.DateField(auto_now_add=True, verbose_name='Создано')),
            ],
            options={
                'verbose_name_plural': 'Просмотры новостей проекта',
                'verbose_name': 'Просмотр новости проекта',
            },
        ),
        migrations.CreateModel(
            name='ElectNewNumbers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.PositiveIntegerField(default=0, verbose_name='Кто заходит')),
                ('new', models.PositiveIntegerField(default=0, verbose_name='Какую новость депутата смотрит')),
                ('platform', models.PositiveIntegerField(default=0, verbose_name='0 Комп, 1 Телефон')),
                ('created', models.DateField(auto_now_add=True, verbose_name='Создано')),
            ],
            options={
                'verbose_name_plural': 'Просмотры новостей чиновника',
                'verbose_name': 'Просмотр новости чиновника',
            },
        ),
        migrations.CreateModel(
            name='ElectNumbers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visitor', models.PositiveIntegerField(default=0, verbose_name='Кто заходит')),
                ('elect', models.PositiveIntegerField(default=0, verbose_name='К какому чиновнику заходит')),
                ('platform', models.PositiveIntegerField(default=0, verbose_name='0 Комп, 1 Телефон')),
                ('created', models.DateField(auto_now_add=True, verbose_name='Создано')),
            ],
            options={
                'verbose_name_plural': 'Просмотры чиновников',
                'verbose_name': 'Просмотр чиновника',
            },
        ),
        migrations.AddIndex(
            model_name='electnumbers',
            index=django.contrib.postgres.indexes.BrinIndex(fields=['created'], name='stst_electn_created_fbb0b1_brin'),
        ),
        migrations.AddIndex(
            model_name='electnewnumbers',
            index=django.contrib.postgres.indexes.BrinIndex(fields=['created'], name='stst_electn_created_afe9b5_brin'),
        ),
        migrations.AddIndex(
            model_name='blognumbers',
            index=django.contrib.postgres.indexes.BrinIndex(fields=['created'], name='stst_blognu_created_734e6d_brin'),
        ),
    ]
