# Generated by Django 2.2.16 on 2020-11-12 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stst', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='electnumbers',
            old_name='visitor',
            new_name='user',
        ),
    ]
