# Generated by Django 3.2 on 2021-04-15 19:35

import django.contrib.postgres.indexes
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stst', '0002_auto_20201112_1656'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserNumbers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visitor', models.PositiveIntegerField(default=0, verbose_name='Кто заходит')),
                ('target', models.PositiveIntegerField(default=0, verbose_name='К кому заходит')),
                ('device', models.CharField(blank=True, choices=[('De', 'Комп'), ('Ph', 'Телефон')], default='De', max_length=5, verbose_name='Оборудование')),
                ('created', models.DateField(auto_now_add=True, verbose_name='Создано')),
            ],
            options={
                'verbose_name': 'Кто к кому заходил',
                'verbose_name_plural': 'Кто к кому заходил',
            },
        ),
        migrations.AddIndex(
            model_name='usernumbers',
            index=django.contrib.postgres.indexes.BrinIndex(fields=['created'], name='stst_usernu_created_c7bca1_brin'),
        ),
    ]
