# Generated by Django 3.2.5 on 2021-08-27 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0004_alter_electnewscategory_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='authoritylist',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Действующий список'),
        ),
        migrations.AddField(
            model_name='authoritylist',
            name='is_in_left_menu',
            field=models.BooleanField(default=False, verbose_name='Выводится в левом меню'),
        ),
    ]
