# Generated by Django 3.2.5 on 2021-09-09 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0005_auto_20210827_1418'),
    ]

    operations = [
        migrations.AddField(
            model_name='authoritylist',
            name='year',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Год четырехзначный'),
        ),
    ]
