# Generated by Django 3.2.5 on 2021-10-09 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0010_alter_medialist_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='medialist',
            name='count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
