# Generated by Django 3.2.5 on 2021-10-30 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0011_medialist_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='medialist',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='media_list_parent', to='lists.medialist', verbose_name='Родительский список'),
        ),
    ]
