# Generated by Django 3.2 on 2021-06-09 17:38

import django.contrib.postgres.indexes
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0002_auto_20210530_1129'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogCreateWorkerManageLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.PositiveIntegerField(default=0, verbose_name='Пользователь')),
                ('manager', models.PositiveIntegerField(default=0, verbose_name='Менеджер')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('action_type', models.CharField(choices=[('CA', 'Добавлен создатель админов блога'), ('DA', 'Удален создатель админов блога'), ('CE', 'Добавлен создатель редакторов блога'), ('DE', 'Удален создатель редакторов блога'), ('CM', 'Добавлен создатель модераторов блога'), ('DM', 'Удален создатель модераторов блога')], editable=False, max_length=5)),
            ],
            options={
                'verbose_name': 'Лог создателя суперменеджера блога',
                'verbose_name_plural': 'Логи создателей суперменеджеров блога',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='BlogManageLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.PositiveIntegerField(default=0, verbose_name='Запись')),
                ('manager', models.PositiveIntegerField(default=0, verbose_name='Менеджер')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('action_type', models.CharField(choices=[('LCLO', 'Список закрыт'), ('ICLO', 'Элемент закрыт'), ('CCLO', 'Комментарий закрыт'), ('LRES', 'Список восстановлен'), ('IRES', 'Элемент восстановлен'), ('CRES', 'Комментарий восстановлен'), ('LREJ', 'Жалоба на список отклонена'), ('IREJ', 'Жалоба на элемент отклонена'), ('CREJ', 'Жалоба на комментарий отклонена'), ('LUNV', 'Проверка на список убрана'), ('IUNV', 'Проверка на элемент убрана'), ('CUNV', 'Проверка на комментарий убрана')], editable=False, max_length=5)),
            ],
            options={
                'verbose_name': 'Лог менеджера блога',
                'verbose_name_plural': 'Логи менеджеров блога',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='BlogWorkerManageLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.PositiveIntegerField(default=0, verbose_name='Пользователь')),
                ('manager', models.PositiveIntegerField(default=0, verbose_name='Менеджер')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('action_type', models.CharField(choices=[('CA', 'Добавлен админ блога'), ('DA', 'Удален админ блога'), ('CE', 'Добавлен редактор блога'), ('DE', 'Удален редактор блога'), ('CM', 'Добавлен модератор блога'), ('DM', 'Удален модератор блога')], editable=False, max_length=5)),
            ],
            options={
                'verbose_name': 'Лог суперменеджера блога',
                'verbose_name_plural': 'Логи супеменеджеров блога',
                'ordering': ['-created'],
            },
        ),
        migrations.AddIndex(
            model_name='blogworkermanagelog',
            index=django.contrib.postgres.indexes.BrinIndex(fields=['created'], name='logs_blogwo_created_a0a51d_brin'),
        ),
        migrations.AddIndex(
            model_name='blogmanagelog',
            index=django.contrib.postgres.indexes.BrinIndex(fields=['created'], name='logs_blogma_created_4dc035_brin'),
        ),
        migrations.AddIndex(
            model_name='blogcreateworkermanagelog',
            index=django.contrib.postgres.indexes.BrinIndex(fields=['created'], name='logs_blogcr_created_8d6788_brin'),
        ),
    ]
