# Generated by Django 3.2.5 on 2021-07-26 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0004_auto_20210720_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogmanagelog',
            name='action_type',
            field=models.CharField(choices=[('LCLO', 'Список закрыт'), ('ICRE', 'Новость создана'), ('IEDI', 'Элемент изменён'), ('ICLO', 'Элемент закрыт'), ('CCLO', 'Комментарий закрыт'), ('LRES', 'Список восстановлен'), ('IRES', 'Элемент восстановлен'), ('CRES', 'Комментарий восстановлен'), ('LREJ', 'Жалоба на список отклонена'), ('IREJ', 'Жалоба на элемент отклонена'), ('CREJ', 'Жалоба на комментарий отклонена'), ('LUNV', 'Проверка на список убрана'), ('IUNV', 'Проверка на элемент убрана'), ('CUNV', 'Проверка на комментарий убрана')], editable=False, max_length=5),
        ),
        migrations.AlterField(
            model_name='electnewmanagelog',
            name='action_type',
            field=models.CharField(choices=[('LCLO', 'Список закрыт'), ('ICRE', 'Активность создана'), ('CCLO', 'Активность опубликована'), ('IEDI', 'Элемент изменён'), ('ICLO', 'Элемент закрыт'), ('IPUB', 'Комментарий закрыт'), ('LRES', 'Список восстановлен'), ('IRES', 'Элемент восстановлен'), ('CRES', 'Комментарий восстановлен'), ('LREJ', 'Жалоба на список отклонена'), ('IREJ', 'Жалоба на элемент отклонена'), ('CREJ', 'Жалоба на комментарий отклонена'), ('LUNV', 'Проверка на список убрана'), ('IUNV', 'Проверка на элемент убрана'), ('CUNV', 'Проверка на комментарий убрана')], editable=False, max_length=5),
        ),
    ]
