# Generated by Django 3.2.5 on 2021-08-11 16:10

import django.contrib.postgres.indexes
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0005_auto_20210726_1949'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationCreateWorkerManageLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.PositiveIntegerField(default=0, verbose_name='Пользователь')),
                ('manager', models.PositiveIntegerField(default=0, verbose_name='Менеджер')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('action_type', models.CharField(choices=[('CA', 'Добавлен создатель админов организаций'), ('DA', 'Удален создатель админов организаций'), ('CE', 'Добавлен создатель редакторов организаций'), ('DE', 'Удален создатель редакторов организаций'), ('CM', 'Добавлен создатель модераторов организаций'), ('DM', 'Удален создатель модераторов организаций')], editable=False, max_length=5)),
            ],
            options={
                'verbose_name': 'Лог создателя суперменеджера организаций',
                'verbose_name_plural': 'Логи создателей суперменеджеров организаций',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='OrganizationManageLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.PositiveIntegerField(default=0, verbose_name='Запись')),
                ('manager', models.PositiveIntegerField(default=0, verbose_name='Менеджер')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('action_type', models.CharField(choices=[('ICLO', 'Элемент закрыт'), ('CCLO', 'Комментарий закрыт'), ('IRES', 'Элемент восстановлен'), ('CRES', 'Комментарий восстановлен'), ('IREJ', 'Жалоба на элемент отклонена'), ('CREJ', 'Жалоба на комментарий отклонена'), ('IUNV', 'Проверка на элемент убрана'), ('CUNV', 'Проверка на комментарий убрана')], editable=False, max_length=5)),
            ],
            options={
                'verbose_name': 'Лог менеджера организаций',
                'verbose_name_plural': 'Логи менеджеров организаций',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='OrganizationWorkerManageLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.PositiveIntegerField(default=0, verbose_name='Пользователь')),
                ('manager', models.PositiveIntegerField(default=0, verbose_name='Менеджер')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('action_type', models.CharField(choices=[('CA', 'Добавлен админ организаций'), ('DA', 'Удален админ организаций'), ('CE', 'Добавлен редактор организаций'), ('DE', 'Удален редактор организаций'), ('CM', 'Добавлен модератор организаций'), ('DM', 'Удален модератор организаций')], editable=False, max_length=5)),
            ],
            options={
                'verbose_name': 'Лог суперменеджера организаций',
                'verbose_name_plural': 'Логи супеменеджеров организаций',
                'ordering': ['-created'],
            },
        ),
        migrations.AlterField(
            model_name='usermanagelog',
            name='action_type',
            field=models.CharField(choices=[('CLO', 'Закрыт'), ('CLOH', 'Восстановлен'), ('SC', 'Вечная заморозка'), ('SH', 'Долгая заморозка'), ('SM', 'Средняя заморозка'), ('SL', 'Краткая заморозка'), ('USH', 'Разморожен'), ('WB', 'Выставлен предупреждающий баннер'), ('NWBH', 'Убран предупреждающий баннер'), ('REJ', 'Жалоба отклонена'), ('UNV', 'Проверка убрана'), ('CRE', 'Создано'), ('PUB', 'Одобрено')], editable=False, max_length=5),
        ),
        migrations.AddIndex(
            model_name='organizationworkermanagelog',
            index=django.contrib.postgres.indexes.BrinIndex(fields=['created'], name='logs_organi_created_1e5c19_brin'),
        ),
        migrations.AddIndex(
            model_name='organizationmanagelog',
            index=django.contrib.postgres.indexes.BrinIndex(fields=['created'], name='logs_organi_created_29d78d_brin'),
        ),
        migrations.AddIndex(
            model_name='organizationcreateworkermanagelog',
            index=django.contrib.postgres.indexes.BrinIndex(fields=['created'], name='logs_organi_created_e83086_brin'),
        ),
    ]
