# Generated by Django 3.2.5 on 2021-08-28 16:14

import django.contrib.postgres.indexes
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0007_auto_20210825_1158'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElectManageLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.PositiveIntegerField(default=0, verbose_name='Депутат')),
                ('manager', models.PositiveIntegerField(default=0, verbose_name='Менеджер')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('action_type', models.CharField(choices=[('ICRE', 'Депутат создан'), ('IEDI', 'Элемент изменён'), ('ICLO', 'Элемент закрыт')], editable=False, max_length=5)),
            ],
            options={
                'verbose_name': 'Лог менеджера депутатов',
                'verbose_name_plural': 'Логи менеджеров депутатов',
                'ordering': ['-created'],
            },
        ),
        migrations.AddIndex(
            model_name='electmanagelog',
            index=django.contrib.postgres.indexes.BrinIndex(fields=['created'], name='logs_electm_created_a8e1bf_brin'),
        ),
    ]
