# Generated by Django 3.2.5 on 2021-10-09 18:33

import django.contrib.postgres.indexes
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0008_auto_20210828_1614'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaManageLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.PositiveIntegerField(default=0, verbose_name='Запись')),
                ('manager', models.PositiveIntegerField(default=0, verbose_name='Менеджер')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('action_type', models.CharField(choices=[('LCRE', 'Список создан'), ('LEDI', 'Список изменен'), ('LDEL', 'Список удален'), ('LREC', 'Список восстановлен'), ('ICRE', 'Элемент создан'), ('IEDI', 'Элемент изменен'), ('IDEL', 'Элемент удален'), ('IREC', 'Элемент восстановлен')], editable=False, max_length=5)),
            ],
            options={
                'verbose_name': 'Лог менеджера медиа-объектов',
                'verbose_name_plural': 'Логи менеджеров медиа-объектов',
                'ordering': ['-created'],
            },
        ),
        migrations.AddIndex(
            model_name='mediamanagelog',
            index=django.contrib.postgres.indexes.BrinIndex(fields=['created'], name='logs_mediam_created_6fa427_brin'),
        ),
    ]
