# Generated by Django 3.2.5 on 2021-11-13 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0010_alter_electnewmanagelog_action_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiomanagelog',
            name='action_type',
            field=models.CharField(choices=[('LCRE', 'Список создан'), ('LEDI', 'Список изменен'), ('LCLO', 'Список закрыт'), ('ICRE', 'Элемент создан'), ('IEDI', 'Элемент изменен'), ('ICLO', 'Элемент закрыт'), ('CCLO', 'Комментарий закрыт'), ('LRES', 'Список восстановлен'), ('IRES', 'Элемент восстановлен'), ('CRES', 'Комментарий восстановлен'), ('LREJ', 'Жалобы на список отклонены'), ('IREJ', 'Жалобы на элемент отклонены'), ('CREJ', 'Жалобы на комментарий отклонены'), ('LUNV', 'Проверка на список убрана'), ('IUNV', 'Проверка на элемент убрана'), ('CUNV', 'Проверка на комментарий убрана')], editable=False, max_length=5),
        ),
        migrations.AlterField(
            model_name='blogmanagelog',
            name='action_type',
            field=models.CharField(choices=[('LCLO', 'Список закрыт'), ('ICRE', 'Новость создана'), ('IEDI', 'Элемент изменён'), ('ICLO', 'Элемент закрыт'), ('CCLO', 'Комментарий закрыт'), ('LRES', 'Список восстановлен'), ('IRES', 'Элемент восстановлен'), ('CRES', 'Комментарий восстановлен'), ('LREJ', 'Жалобы на список отклонены'), ('IREJ', 'Жалобы на элемент отклонены'), ('CREJ', 'Жалобы на комментарий отклонены'), ('LUNV', 'Проверка на список убрана'), ('IUNV', 'Проверка на элемент убрана'), ('CUNV', 'Проверка на комментарий убрана')], editable=False, max_length=5),
        ),
        migrations.AlterField(
            model_name='communitymanagelog',
            name='action_type',
            field=models.CharField(choices=[('CLO', 'Закрыт'), ('CLOH', 'Восстановлен'), ('SC', 'Вечная заморозка'), ('SH', 'Долгая заморозка'), ('SM', 'Средняя заморозка'), ('SL', 'Краткая заморозка'), ('USH', 'Разморожен'), ('WB', 'Выставлен предупреждающий баннер'), ('NWBH', 'Убран предупреждающий баннер'), ('REJ', 'Жалобы отклонены'), ('UNV', 'Проверка убрана')], editable=False, max_length=5),
        ),
        migrations.AlterField(
            model_name='docmanagelog',
            name='action_type',
            field=models.CharField(choices=[('LCRE', 'Список создан'), ('LEDI', 'Список изменен'), ('LCLO', 'Список закрыт'), ('ICRE', 'Элемент создан'), ('IEDI', 'Элемент изменен'), ('ICLO', 'Элемент закрыт'), ('CCLO', 'Комментарий закрыт'), ('LRES', 'Список восстановлен'), ('IRES', 'Элемент восстановлен'), ('CRES', 'Комментарий восстановлен'), ('LREJ', 'Жалобы на список отклонены'), ('IREJ', 'Жалобы на элемент отклонены'), ('CREJ', 'Жалобы на комментарий отклонены'), ('LUNV', 'Проверка на список убрана'), ('IUNV', 'Проверка на элемент убрана'), ('CUNV', 'Проверка на комментарий убрана')], editable=False, max_length=5),
        ),
        migrations.AlterField(
            model_name='electnewmanagelog',
            name='action_type',
            field=models.CharField(choices=[('LCLO', 'Список закрыт'), ('ICRE', 'Активность создана'), ('IPUB', 'Активность опубликована'), ('IEDI', 'Элемент изменён'), ('ICLO', 'Элемент закрыт'), ('CCLO', 'Комментарий закрыт'), ('LRES', 'Список восстановлен'), ('IRES', 'Элемент восстановлен'), ('CRES', 'Комментарий восстановлен'), ('LREJ', 'Жалобы на список отклонены'), ('IREJ', 'Жалобы на элемент отклонены'), ('CREJ', 'Жалобы на комментарий отклонены'), ('LUNV', 'Проверка на список убрана'), ('IUNV', 'Проверка на элемент убрана'), ('CUNV', 'Проверка на комментарий убрана')], editable=False, max_length=5),
        ),
        migrations.AlterField(
            model_name='organizationmanagelog',
            name='action_type',
            field=models.CharField(choices=[('ICLO', 'Элемент закрыт'), ('CCLO', 'Комментарий закрыт'), ('IRES', 'Элемент восстановлен'), ('CRES', 'Комментарий восстановлен'), ('IREJ', 'Жалобы на элемент отклонены'), ('CREJ', 'Жалобы на комментарий отклонены'), ('IUNV', 'Проверка на элемент убрана'), ('CUNV', 'Проверка на комментарий убрана')], editable=False, max_length=5),
        ),
        migrations.AlterField(
            model_name='photomanagelog',
            name='action_type',
            field=models.CharField(choices=[('LCRE', 'Список создан'), ('LEDI', 'Список изменен'), ('LCLO', 'Список закрыт'), ('ICRE', 'Элемент создан'), ('IEDI', 'Элемент изменен'), ('ICLO', 'Элемент закрыт'), ('CCLO', 'Комментарий закрыт'), ('LRES', 'Список восстановлен'), ('IRES', 'Элемент восстановлен'), ('CRES', 'Комментарий восстановлен'), ('LREJ', 'Жалобы на список отклонены'), ('IREJ', 'Жалобы на элемент отклонены'), ('CREJ', 'Жалобы на комментарий отклонены'), ('LUNV', 'Проверка на список убрана'), ('IUNV', 'Проверка на элемент убрана'), ('CUNV', 'Проверка на комментарий убрана')], editable=False, max_length=5),
        ),
        migrations.AlterField(
            model_name='surveymanagelog',
            name='action_type',
            field=models.CharField(choices=[('LCRE', 'Список создан'), ('LEDI', 'Список изменен'), ('LCLO', 'Список закрыт'), ('ICRE', 'Элемент создан'), ('IEDI', 'Элемент изменен'), ('ICLO', 'Элемент закрыт'), ('CCLO', 'Комментарий закрыт'), ('LRES', 'Список восстановлен'), ('IRES', 'Элемент восстановлен'), ('CRES', 'Комментарий восстановлен'), ('LREJ', 'Жалобы на список отклонены'), ('IREJ', 'Жалобы на элемент отклонены'), ('CREJ', 'Жалоба на комментарий отклонены'), ('LUNV', 'Проверка на список убрана'), ('IUNV', 'Проверка на элемент убрана'), ('CUNV', 'Проверка на комментарий убрана')], editable=False, max_length=5),
        ),
        migrations.AlterField(
            model_name='usermanagelog',
            name='action_type',
            field=models.CharField(choices=[('CLO', 'Закрыт'), ('CLOH', 'Восстановлен'), ('SC', 'Вечная заморозка'), ('SH', 'Долгая заморозка'), ('SM', 'Средняя заморозка'), ('SL', 'Краткая заморозка'), ('USH', 'Разморожен'), ('WB', 'Выставлен предупреждающий баннер'), ('NWBH', 'Убран предупреждающий баннер'), ('REJ', 'Жалобы отклонены'), ('UNV', 'Проверка убрана'), ('CRE', 'Создано'), ('PUB', 'Одобрено')], editable=False, max_length=5),
        ),
        migrations.AlterField(
            model_name='videomanagelog',
            name='action_type',
            field=models.CharField(choices=[('LCRE', 'Список создан'), ('LEDI', 'Список изменен'), ('LCLO', 'Список закрыт'), ('ICRE', 'Элемент создан'), ('IEDI', 'Элемент изменен'), ('ICLO', 'Элемент закрыт'), ('CCLO', 'Комментарий закрыт'), ('LRES', 'Список восстановлен'), ('IRES', 'Элемент восстановлен'), ('CRES', 'Комментарий восстановлен'), ('LREJ', 'Жалобы на список отклонены'), ('IREJ', 'Жалобы на элемент отклонены'), ('CREJ', 'Жалобы на комментарий отклонены'), ('LUNV', 'Проверка на список убрана'), ('IUNV', 'Проверка на элемент убрана'), ('CUNV', 'Проверка на комментарий убрана')], editable=False, max_length=5),
        ),
    ]
