# Generated by Django 3.2.11 on 2022-02-06 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0011_auto_20211113_1916'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MediaManageLog',
        ),
    ]
