# Generated by Django 3.2.5 on 2021-08-31 16:40

import autoslug.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('region', '0006_auto_20210809_1319'),
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='name', unique=True)),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядковый номер')),
                ('point', models.PositiveIntegerField(default=0, verbose_name='Общее количество кармы')),
                ('total_costs', models.PositiveIntegerField(default=0, verbose_name='Общие доходы граждан')),
                ('total_revenue', models.PositiveIntegerField(default=0, verbose_name='Общие расходы граждан')),
                ('total_voters', models.CharField(max_length=50, verbose_name='Всего избирателей')),
                ('total_place', models.CharField(max_length=50, verbose_name='Всего мест')),
                ('total_candidate', models.CharField(max_length=50, verbose_name='Всего кандидатов')),
                ('man_procent', models.CharField(max_length=50, verbose_name='Процент мужчин')),
                ('total_er', models.CharField(max_length=50, verbose_name='Всего из Единой России')),
                ('total_kprf', models.CharField(max_length=50, verbose_name='Всего из КПРФ')),
                ('total_ldpr', models.CharField(max_length=50, verbose_name='Всего из ЛДПР')),
                ('total_sr', models.CharField(max_length=50, verbose_name='Всего из Справедливой России')),
                ('total_self', models.CharField(max_length=50, verbose_name='Всего самовыдвиженцев')),
                ('link', models.CharField(max_length=50, verbose_name='Ссылка для парсинга')),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='districts_region', to='region.region', verbose_name='Регион')),
            ],
            options={
                'verbose_name': 'District',
                'verbose_name_plural': 'District',
                'ordering': ['order', 'name'],
            },
        ),
    ]
