# Generated by Django 3.2 on 2021-05-16 18:52

from django.conf import settings
import django.contrib.postgres.indexes
from django.db import migrations, models
import django.db.models.deletion
import imagekit.models.fields
import users.helpers
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('communities', '0002_communityfollow'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=250, verbose_name='Вариант ответа')),
            ],
            options={
                'verbose_name': 'Вариант ответа',
                'verbose_name_plural': 'Варианты ответа',
            },
        ),
        migrations.CreateModel(
            name='SurveyVote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, related_name='user_answer', to='survey.answer', verbose_name='Опрос')),
                ('user', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, related_name='user_voter', to=settings.AUTH_USER_MODEL, verbose_name='Участник опроса')),
            ],
            options={
                'verbose_name': 'Голос',
                'verbose_name_plural': 'Голоса',
            },
        ),
        migrations.CreateModel(
            name='SurveyList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('MAI', 'Основной'), ('LIS', 'Пользовательский'), ('MAN', 'Созданный персоналом'), ('_PRO', 'Обработка'), ('_DEL', 'Удалённый'), ('_DELM', 'Удалённый менеджерский'), ('_CLO', 'Закрытый менеджером'), ('_CLOP', 'Закрытый приватный'), ('_CLOM', 'Закрытый основной'), ('_CLOMA', 'Закрытый менеджерский')], default='_PRO', max_length=6, verbose_name='Тип списка')),
                ('order', models.PositiveIntegerField(default=0)),
                ('uuid', models.UUIDField(default=uuid.uuid4, verbose_name='uuid')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='Описание')),
                ('communities', models.ManyToManyField(blank=True, related_name='_survey_surveylist_communities_+', to='communities.Community')),
                ('community', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='community_surveylist', to='communities.community', verbose_name='Сообщество')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creator_surveylist', to=settings.AUTH_USER_MODEL, verbose_name='Создатель')),
                ('users', models.ManyToManyField(blank=True, related_name='_survey_surveylist_users_+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'список опросов',
                'verbose_name_plural': 'списки опросов',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Название')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('is_anonymous', models.BooleanField(default=False, verbose_name='Анонимный')),
                ('is_multiple', models.BooleanField(default=False, verbose_name='Несколько вариантов')),
                ('is_no_edited', models.BooleanField(default=False, verbose_name='Запрет отмены голоса')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядковый номер')),
                ('image', imagekit.models.fields.ProcessedImageField(blank=True, upload_to=users.helpers.upload_to_user_directory, verbose_name='Главное изображение')),
                ('status', models.CharField(choices=[('_PRO', 'Обработка'), ('PUB', 'Созданный персоналом'), ('MAN', 'Опубликовано'), ('_DEL', 'Удалено'), ('_DELM', 'Удален менеджерский'), ('_CLO', 'Закрыто модератором'), ('_CLOM', 'Закрыт менеджерский')], default='_PRO', max_length=5)),
                ('time_end', models.DateTimeField(blank=True, null=True, verbose_name='Дата окончания')),
                ('vote', models.PositiveIntegerField(default=0, verbose_name='Кол-во голосов')),
                ('voter', models.PositiveIntegerField(default=0, verbose_name='Кол-во людей')),
                ('repost', models.PositiveIntegerField(default=0, verbose_name='Кол-во репостов')),
                ('community', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='survey_community', to='communities.community', verbose_name='Сообщество')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='survey_creator', to=settings.AUTH_USER_MODEL, verbose_name='Создатель')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='survey_list', to='survey.surveylist', verbose_name='Список')),
            ],
            options={
                'verbose_name': 'Опрос',
                'verbose_name_plural': 'Опросы',
            },
        ),
        migrations.AddField(
            model_name='answer',
            name='survey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='survey.survey', verbose_name='Опрос'),
        ),
        migrations.AddIndex(
            model_name='surveyvote',
            index=models.Index(fields=['answer', 'user'], name='survey_surv_answer__c02d10_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='surveyvote',
            unique_together={('user', 'answer')},
        ),
        migrations.AddIndex(
            model_name='survey',
            index=django.contrib.postgres.indexes.BrinIndex(fields=['created'], name='survey_surv_created_7a1fda_brin'),
        ),
    ]
