# Generated by Django 3.2 on 2021-05-22 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='survey',
            old_name='status',
            new_name='type',
        ),
    ]
