# Generated by Django 3.2.5 on 2021-10-10 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0004_alter_surveylist_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='is_survey',
            field=models.BooleanField(default=True),
        ),
    ]
