# Generated by Django 3.2 on 2021-04-22 13:55

from django.db import migrations, models
import video.helpers


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='file',
            field=models.FileField(default='', upload_to=video.helpers.upload_to_video_directory, validators=[video.helpers.validate_file_extension], verbose_name='Видеозапись'),
            preserve_default=False,
        ),
    ]
