# Generated by Django 3.2 on 2021-04-22 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0002_video_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='album',
            new_name='list',
        ),
        migrations.RenameField(
            model_name='videoalbum',
            old_name='title',
            new_name='name',
        ),
        migrations.AddField(
            model_name='videoalbum',
            name='description',
            field=models.CharField(blank=True, max_length=200, verbose_name='Описание'),
        ),
    ]
