# Generated by Django 3.2 on 2021-05-13 18:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('communities', '0001_initial'),
        ('video', '0005_alter_videoalbum_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='community',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='video_community', to='communities.community', verbose_name='Сообщество'),
        ),
        migrations.AddField(
            model_name='videoalbum',
            name='communities',
            field=models.ManyToManyField(blank=True, related_name='_video_videoalbum_communities_+', to='communities.Community'),
        ),
        migrations.AddField(
            model_name='videoalbum',
            name='community',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='video_lists_community', to='communities.community', verbose_name='Сообщество'),
        ),
        migrations.AlterField(
            model_name='videoalbum',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_list_creator', to=settings.AUTH_USER_MODEL, verbose_name='Создатель'),
        ),
        migrations.AlterField(
            model_name='videoalbum',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='_video_videoalbum_users_+', to=settings.AUTH_USER_MODEL),
        ),
    ]
