# Generated by Django 3.2 on 2021-05-16 20:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('communities', '0002_communityfollow'),
        ('video', '0006_auto_20210513_1823'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, verbose_name='uuid')),
                ('name', models.CharField(max_length=250, verbose_name='Название')),
                ('order', models.PositiveIntegerField(default=0)),
                ('type', models.CharField(choices=[('MAI', 'Основной'), ('LIS', 'Пользовательский'), ('PRI', 'Приватный'), ('MAN', 'Созданный персоналом'), ('_PRO', 'Обработка'), ('_DEL', 'Удалённый'), ('_DELP', 'Удалённый приватный'), ('_DELM', 'Удалённый менеджерский'), ('_CLO', 'Закрытый менеджером'), ('_CLOP', 'Закрытый приватный'), ('_CLOM', 'Закрытый основной'), ('_CLOMA', 'Закрытый менеджерский')], default='_PRO', max_length=6, verbose_name='Тип альбома')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='Описание')),
                ('communities', models.ManyToManyField(blank=True, related_name='_video_videolist_communities_+', to='communities.Community')),
                ('community', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='video_lists_community', to='communities.community', verbose_name='Сообщество')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_list_creator', to=settings.AUTH_USER_MODEL, verbose_name='Создатель')),
                ('users', models.ManyToManyField(blank=True, related_name='_video_videolist_users_+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Видеоальбом',
                'verbose_name_plural': 'Видеоальбомы',
                'ordering': ['order'],
            },
        ),
        migrations.DeleteModel(
            name='VideoAlbum',
        ),
        migrations.AlterField(
            model_name='video',
            name='list',
            field=models.ManyToManyField(blank=True, related_name='video_list', to='video.VideoList', verbose_name='Альбом'),
        ),
    ]
