# Generated by Django 3.2 on 2021-05-22 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0008_auto_20210521_1906'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='status',
            new_name='type',
        ),
    ]
