# Generated by Django 3.2.5 on 2021-10-10 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0015_alter_video_media_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='is_doc',
            field=models.BooleanField(default=True),
        ),
    ]
