# Generated by Django 3.2.5 on 2021-10-31 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0016_video_is_doc'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='is_doc',
            new_name='is_video',
        ),
    ]
