# Generated by Django 3.2.5 on 2021-11-13 19:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quan', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Support',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('QU', 'Вопрос / предложение'), ('CO', 'Сотрудничество'), ('TP', 'Тех. проблема'), ('PA', 'Помощь проекту')], default='QU', max_length=2)),
                ('description', models.CharField(blank=True, max_length=500, verbose_name='Описание')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='support_creator', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Голос',
                'verbose_name_plural': 'Голоса',
            },
        ),
        migrations.CreateModel(
            name='SupportImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', imagekit.models.fields.ProcessedImageField(upload_to='support/', verbose_name='Изображение')),
                ('support', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='quan.support')),
            ],
        ),
    ]
