# Generated by Django 3.2.5 on 2021-11-14 10:56

from django.db import migrations, models
import django.db.models.deletion
import docs.helpers


class Migration(migrations.Migration):

    dependencies = [
        ('quan', '0002_support_supportimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='support/', validators=[docs.helpers.validate_file_extension], verbose_name='Файл')),
                ('support', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='quan.support')),
            ],
        ),
        migrations.DeleteModel(
            name='SupportImage',
        ),
    ]
