# Generated by Django 3.2.5 on 2021-11-14 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quan', '0003_auto_20211114_1056'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='support',
            options={'verbose_name': 'Обращение в тех. поддержку', 'verbose_name_plural': 'Обращения в тех. поддержку'},
        ),
        migrations.AlterField(
            model_name='support',
            name='description',
            field=models.TextField(blank=True, max_length=3000, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='support',
            name='type',
            field=models.CharField(choices=[('TP', 'Обращение в техподеержку'), ('QU', 'Вопрос / предложение'), ('CO', 'Сотрудничество'), ('PA', 'Помощь проекту')], default='QU', max_length=2, verbose_name='Тема'),
        ),
    ]
