# Generated by Django 3.2.5 on 2021-11-14 16:12

import datetime
import django.contrib.postgres.indexes
from django.db import migrations, models
import quan.helpers


class Migration(migrations.Migration):

    dependencies = [
        ('quan', '0004_auto_20211114_1456'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='support',
            options={'ordering': ['-created'], 'verbose_name': 'Обращение в тех. поддержку', 'verbose_name_plural': 'Обращения в тех. поддержку'},
        ),
        migrations.AddField(
            model_name='support',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 14, 16, 12, 34, 191480), verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='support',
            name='type',
            field=models.CharField(choices=[('TP', 'Обращение в техподдержку'), ('QU', 'Вопрос / предложение'), ('CO', 'Сотрудничество'), ('PA', 'Помощь проекту')], default='QU', max_length=2, verbose_name='Тема'),
        ),
        migrations.AlterField(
            model_name='supportfile',
            name='file',
            field=models.FileField(upload_to='support/', validators=[quan.helpers.validate_file_extension], verbose_name='Файл'),
        ),
        migrations.AddIndex(
            model_name='support',
            index=django.contrib.postgres.indexes.BrinIndex(fields=['created'], name='quan_suppor_created_07e828_brin'),
        ),
    ]
