# Generated by Django 3.2.5 on 2021-11-14 16:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('quan', '0005_auto_20211114_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='support',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Создано'),
        ),
    ]
