# Generated by Django 3.2.5 on 2021-11-15 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quan', '0007_alter_support_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='support',
            name='type',
            field=models.CharField(choices=[('CH', 'Для правообладателей'), ('TP', 'Обращение в техподдержку'), ('QU', 'Вопрос / предложение'), ('CO', 'Сотрудничество'), ('PA', 'Помощь проекту')], default='QU', max_length=2, verbose_name='Тема'),
        ),
    ]
