# Generated by Django 3.2.5 on 2021-11-15 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quan', '0008_alter_support_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='support',
            name='is_reed',
            field=models.BooleanField(default=False, verbose_name='Прочитано'),
        ),
    ]
