# Generated by Django 3.2.5 on 2021-11-15 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quan', '0009_support_is_reed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='support',
            old_name='is_reed',
            new_name='is_read',
        ),
    ]
