# Generated by Django 2.2.16 on 2020-10-23 17:10

from django.db import migrations, models
import django.db.models.deletion
import imagekit.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lists', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Elect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='ФИО')),
                ('image', imagekit.models.fields.ProcessedImageField(upload_to='elect/%Y/%m/%d/', verbose_name='Аватар')),
                ('description', models.CharField(blank=True, max_length=500, verbose_name='Описание')),
                ('birthday', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
                ('authorization', models.DateField(blank=True, null=True, verbose_name='Дата наделения полномочиями')),
                ('term_of_office', models.DateField(blank=True, null=True, verbose_name='Срок окончания полномочий')),
                ('election_information', models.CharField(blank=True, max_length=100, verbose_name='Сведения об избрании')),
                ('fraction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lists.Fraction', verbose_name='Фракции')),
                ('list', models.ManyToManyField(blank=True, related_name='elect_list', to='lists.AuthorityList', verbose_name='Орган гос. власти')),
                ('region', models.ManyToManyField(blank=True, related_name='elect_region', to='lists.Region', verbose_name='Регион, за которым закреплен депутат')),
            ],
            options={
                'verbose_name': 'Чиновник',
                'verbose_name_plural': 'Чиновники',
            },
        ),
        migrations.CreateModel(
            name='LinkElect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Текст ссылки')),
                ('link', models.URLField(max_length=255, verbose_name='Ссылки')),
                ('elect', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='elect.Elect', verbose_name='Чиновник')),
            ],
            options={
                'verbose_name': 'Ссылка для чиновника',
                'verbose_name_plural': 'Ссылки',
            },
        ),
        migrations.CreateModel(
            name='EducationElect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('year', models.PositiveSmallIntegerField(default=0, verbose_name='Год')),
                ('elect', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='elect.Elect', verbose_name='Чиновник')),
            ],
            options={
                'verbose_name': 'Ссылка для чиновника',
                'verbose_name_plural': 'Ссылки',
            },
        ),
    ]
