# Generated by Django 2.2.16 on 2020-10-26 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elect', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='educationelect',
            options={'verbose_name': 'Образование чиновника', 'verbose_name_plural': 'Образование'},
        ),
    ]
