# Generated by Django 2.2.16 on 2020-10-28 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elect', '0002_auto_20201026_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elect',
            name='authorization',
            field=models.CharField(max_length=100, null=True, verbose_name='Дата наделения полномочиями'),
        ),
        migrations.AlterField(
            model_name='elect',
            name='birthday',
            field=models.CharField(max_length=100, null=True, verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='elect',
            name='term_of_office',
            field=models.CharField(max_length=100, null=True, verbose_name='Срок окончания полномочий'),
        ),
    ]
