# Generated by Django 2.2.16 on 2020-11-02 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elect', '0003_auto_20201028_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educationelect',
            name='year',
            field=models.CharField(max_length=10, verbose_name='Год'),
        ),
    ]
