# Generated by Django 2.2.16 on 2020-11-02 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elect', '0004_auto_20201102_1128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elect',
            name='election_information',
            field=models.CharField(blank=True, max_length=200, verbose_name='Сведения об избрании'),
        ),
    ]
