# Generated by Django 2.2.16 on 2020-11-04 16:57

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('elect', '0005_auto_20201102_1333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elect',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(blank=True, upload_to='elect/%Y/%m/%d/', verbose_name='Аватар'),
        ),
    ]
