# Generated by Django 2.2.16 on 2020-11-11 19:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('elect', '0006_auto_20201104_1657'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscribeElect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('elect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elect_subscribe', to='elect.Elect', verbose_name='Чиновник')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_subscribe', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
        migrations.AddIndex(
            model_name='subscribeelect',
            index=models.Index(fields=['elect', 'user'], name='elect_subsc_elect_i_00a602_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='subscribeelect',
            unique_together={('elect', 'user')},
        ),
    ]
