# Generated by Django 3.2 on 2021-04-15 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('region', '0001_initial'),
        ('elect', '0007_auto_20201111_1901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elect',
            name='region',
            field=models.ManyToManyField(blank=True, related_name='elect_region', to='region.Region', verbose_name='Регион, за которым закреплен депутат'),
        ),
    ]
