# Generated by Django 3.2.5 on 2021-08-26 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elect', '0009_auto_20210523_1712'),
    ]

    operations = [
        migrations.AddField(
            model_name='elect',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Может добавлять рекламодателей докуметов'),
        ),
    ]
