# Generated by Django 3.2.5 on 2021-08-26 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elect', '0010_elect_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elect',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активный депутат'),
        ),
    ]
