# Generated by Django 3.2.5 on 2021-08-27 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('elect', '0011_alter_elect_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElectStat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lgbt', models.SmallIntegerField(choices=[(1, 'Молодец'), (0, 'Нормальный'), (-1, 'Не молодец')], default=0, verbose_name='Отношение к ЛГБТ')),
                ('yuvenal', models.SmallIntegerField(choices=[(1, 'Молодец'), (0, 'Нормальный'), (-1, 'Не молодец')], default=0, verbose_name='Отношение к ювеналке')),
                ('med_fascism', models.SmallIntegerField(choices=[(1, 'Молодец'), (0, 'Нормальный'), (-1, 'Не молодец')], default=0, verbose_name='Отношение к мед. фашизму')),
                ('abort', models.SmallIntegerField(choices=[(1, 'Молодец'), (0, 'Нормальный'), (-1, 'Не молодец')], default=0, verbose_name='Отношение к абортам')),
                ('educations', models.SmallIntegerField(choices=[(1, 'Молодец'), (0, 'Нормальный'), (-1, 'Не молодец')], default=0, verbose_name='Отношение к образованию')),
                ('express_loans', models.SmallIntegerField(choices=[(1, 'Молодец'), (0, 'Нормальный'), (-1, 'Не молодец')], default=0, verbose_name='Отношение к экспресс-судам')),
                ('sbn', models.SmallIntegerField(choices=[(1, 'Молодец'), (0, 'Нормальный'), (-1, 'Не молодец')], default=0, verbose_name='Отношение к СБН')),
                ('surrogat_mom', models.SmallIntegerField(choices=[(1, 'Молодец'), (0, 'Нормальный'), (-1, 'Не молодец')], default=0, verbose_name='Отношение к суррогатному материнству')),
                ('elect', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='elect_stat', to='elect.elect', verbose_name='Пользователь')),
            ],
        ),
    ]
