# Generated by Django 3.2.5 on 2021-08-27 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('city', '0002_auto_20210809_1319'),
        ('region', '0006_auto_20210809_1319'),
        ('elect', '0012_electstat'),
    ]

    operations = [
        migrations.AddField(
            model_name='elect',
            name='city',
            field=models.ManyToManyField(blank=True, related_name='elect_city', to='city.City', verbose_name='Города, за которым закреплен депутат'),
        ),
        migrations.AlterField(
            model_name='elect',
            name='region',
            field=models.ManyToManyField(blank=True, related_name='elect_region', to='region.Region', verbose_name='Регионы, за которым закреплен депутат'),
        ),
    ]
