# Generated by Django 3.2.5 on 2021-08-28 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elect', '0013_auto_20210827_1418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elect',
            name='authorization',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Дата наделения полномочиями'),
        ),
        migrations.AlterField(
            model_name='elect',
            name='birthday',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='elect',
            name='term_of_office',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Срок окончания полномочий'),
        ),
    ]
