# Generated by Django 3.2.5 on 2021-08-30 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elect', '0014_auto_20210828_1706'),
    ]

    operations = [
        migrations.AddField(
            model_name='elect',
            name='post',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Должность'),
        ),
        migrations.AlterField(
            model_name='elect',
            name='description',
            field=models.CharField(blank=True, max_length=500, verbose_name='Образование'),
        ),
    ]
