# Generated by Django 3.2.5 on 2021-09-04 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elect', '0014_auto_20210828_1706'),
    ]

    operations = [
       
       
        migrations.AlterField(
            model_name='elect',
            name='description',
            field=models.CharField(blank=True, max_length=500, verbose_name='Образование'),
        ),
    ]
