# Generated by Django 3.2.5 on 2021-08-31 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('district', '0001_initial'),
        ('elect', '0015_auto_20210830_1249'),
    ]

    operations = [
        migrations.AddField(
            model_name='elect',
            name='district',
            field=models.ManyToManyField(blank=True, related_name='elect_district', to='district.District', verbose_name='Районы, за которым закреплен депутат'),
        ),
    ]
