# Generated by Django 3.2.5 on 2021-09-01 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elect', '0016_elect_district'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elect',
            name='post',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='Должность'),
        ),
    ]
