# Generated by Django 3.2.5 on 2021-09-04 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elect', '0017_elect_old'),
    ]

    operations = [
        migrations.AddField(
            model_name='elect',
            name='is_new',
            field=models.BooleanField(default=False, verbose_name='Старый депутат'),
        ),
    ]
