# Generated by Django 3.2.5 on 2021-09-09 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('okrug', '0001_initial'),
        ('elect', '0019_alter_elect_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='elect',
            name='okrug',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='okrug.okrug', verbose_name='Одномандатный избирательный округ'),
        ),
    ]
