# Generated by Django 3.2.5 on 2021-09-09 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elect', '0020_elect_okrug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elect',
            name='description',
            field=models.CharField(blank=True, max_length=700, verbose_name='Образование'),
        ),
    ]
