# Generated by Django 3.2.5 on 2021-09-11 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elect', '0021_alter_elect_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='elect',
            name='address',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Адрес (приёмная)'),
        ),
        migrations.AddField(
            model_name='elect',
            name='fb',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Ссылка на Facebook'),
        ),
        migrations.AddField(
            model_name='elect',
            name='ig',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Ссылка на Instagram'),
        ),
        migrations.AddField(
            model_name='elect',
            name='mail',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Электронная почта'),
        ),
        migrations.AddField(
            model_name='elect',
            name='phone',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Телефон'),
        ),
        migrations.AddField(
            model_name='elect',
            name='tg',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Ссылка на Telegram'),
        ),
        migrations.AddField(
            model_name='elect',
            name='tw',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Ссылка на Twitter'),
        ),
        migrations.AddField(
            model_name='elect',
            name='vk',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Ссылка на VK'),
        ),
    ]
