# Generated by Django 3.2.5 on 2021-09-13 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elect', '0022_auto_20210911_1910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elect',
            name='address',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Адрес (приёмная)'),
            preserve_default=False,
        ),
    ]
