# Generated by Django 3.2.5 on 2021-09-13 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elect', '0023_alter_elect_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elect',
            name='fb',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Ссылка на Facebook'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='elect',
            name='ig',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Ссылка на Instagram'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='elect',
            name='mail',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Электронная почта'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='elect',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Телефон'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='elect',
            name='tg',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Ссылка на Telegram'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='elect',
            name='tw',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Ссылка на Twitter'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='elect',
            name='vk',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Ссылка на VK'),
            preserve_default=False,
        ),
    ]
