# Generated by Django 3.2.5 on 2021-09-25 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elect', '0025_auto_20210913_1217'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='elect',
            name='is_new',
        ),
    ]
