# Generated by Django 3.2.5 on 2021-09-26 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elect', '0026_remove_elect_is_new'),
    ]

    operations = [
        migrations.AddField(
            model_name='elect',
            name='site',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Сайт'),
        ),
    ]
