# Generated by Django 3.2.5 on 2021-10-24 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elect', '0027_elect_site'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elect',
            name='fb',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='Ссылка на Facebook'),
        ),
        migrations.AlterField(
            model_name='elect',
            name='ig',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='Ссылка на Instagram'),
        ),
        migrations.AlterField(
            model_name='elect',
            name='mail',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='Электронная почта'),
        ),
        migrations.AlterField(
            model_name='elect',
            name='site',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Сайт'),
        ),
        migrations.AlterField(
            model_name='elect',
            name='tg',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='Ссылка на Telegram'),
        ),
        migrations.AlterField(
            model_name='elect',
            name='tw',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='Ссылка на Twitter'),
        ),
        migrations.AlterField(
            model_name='elect',
            name='vk',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='Ссылка на VK'),
        ),
    ]
