# Generated by Django 3.2.5 on 2021-11-21 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elect', '0030_elect_i_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elect',
            name='address',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Адрес (приёмная)'),
        ),
        migrations.AlterField(
            model_name='elect',
            name='i_address',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Интернет-приёмная'),
        ),
        migrations.AlterField(
            model_name='elect',
            name='site',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='Сайт'),
        ),
    ]
