# Generated by Django 3.2.5 on 2021-11-21 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elect', '0031_auto_20211121_1128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elect',
            name='address',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='Адрес (приёмная)'),
        ),
        migrations.AlterField(
            model_name='elect',
            name='i_address',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='Интернет-приёмная'),
        ),
    ]
