# Generated by Django 3.2 on 2021-04-16 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notify', '0002_auto_20210415_1935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notify',
            name='status',
            field=models.CharField(choices=[('U', 'Не прочитано'), ('R', 'Прочитано'), ('D', 'Удалено'), ('C', 'Закрыто')], default='U', max_length=1, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='notify',
            name='verb',
            field=models.CharField(choices=[('ITE', ' разместил'), ('COM', ' оставил комментарий'), ('WCOM', ' оставила комментарий'), ('GCOM', ' оставили комментарий'), ('REP', ' ответил на'), ('WREP', ' ответила на'), ('GREP', ' ответили на'), ('LIK', ' оценил'), ('WLIK', ' оценила'), ('GLIK', ' оценили'), ('DIS', ' не оценил'), ('WDIS', ' не оценила'), ('GDIS', ' не оценили'), ('INS', ' считает, что'), ('WINS', ' считает, что'), ('GINS', ' считает, что'), ('LCO', ' оценил'), ('WLCO', ' оценила '), ('GLCO', ' оценили'), ('LRE', ' оценил'), ('WLRE', ' оценила'), ('GLRE', ' оценили'), ('SVO', ' участвовал в опросе'), ('WSVO', ' участвовала в опросе'), ('GSVO', ' участвовали в опросе'), ('CRE', ' подал заявку в'), ('WCRE', ' подала заявку в'), ('GCRE', ' подали заявку в'), ('CCO', ' принят в'), ('WCCO', ' принята'), ('GCCO', ' приняты'), ('REG', ' зарегистрировался'), ('WREG', ' зарегистрировалась'), ('GREG', ' зарегистрировались')], max_length=5, verbose_name='Тип уведомления'),
        ),
        migrations.AlterField(
            model_name='wall',
            name='status',
            field=models.CharField(choices=[('U', 'Не прочитано'), ('R', 'Прочитано'), ('D', 'Удалено'), ('C', 'Закрыто')], default='U', max_length=1, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='wall',
            name='verb',
            field=models.CharField(choices=[('ITE', ' разместил'), ('COM', ' оставил комментарий'), ('WCOM', ' оставила комментарий'), ('GCOM', ' оставили комментарий'), ('REP', ' ответил на'), ('WREP', ' ответила на'), ('GREP', ' ответили на'), ('LIK', ' оценил'), ('WLIK', ' оценила'), ('GLIK', ' оценили'), ('DIS', ' не оценил'), ('WDIS', ' не оценила'), ('GDIS', ' не оценили'), ('INS', ' считает, что'), ('WINS', ' считает, что'), ('GINS', ' считает, что'), ('LCO', ' оценил'), ('WLCO', ' оценила '), ('GLCO', ' оценили'), ('LRE', ' оценил'), ('WLRE', ' оценила'), ('GLRE', ' оценили'), ('SVO', ' участвовал в опросе'), ('WSVO', ' участвовала в опросе'), ('GSVO', ' участвовали в опросе'), ('CRE', ' подал заявку в'), ('WCRE', ' подала заявку в'), ('GCRE', ' подали заявку в'), ('CCO', ' принят в'), ('WCCO', ' принята'), ('GCCO', ' приняты'), ('REG', ' зарегистрировался'), ('WREG', ' зарегистрировалась'), ('GREG', ' зарегистрировались')], max_length=5, verbose_name='Тип уведомления'),
        ),
    ]
