# Generated by Django 3.2 on 2021-04-20 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notify', '0003_auto_20210416_1913'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notify',
            name='attach',
        ),
        migrations.RemoveField(
            model_name='wall',
            name='attach',
        ),
        migrations.AddField(
            model_name='notify',
            name='object_id',
            field=models.PositiveIntegerField(default=0, verbose_name='id объекта'),
        ),
        migrations.AddField(
            model_name='notify',
            name='type',
            field=models.CharField(choices=[('USE', 'Пользователь'), ('COM', 'Сообщество'), ('MUL', 'Плейлист'), ('MUS', 'Трек'), ('ELN', 'Активность'), ('ELNC', 'Коммент к активности'), ('BLO', 'Новость'), ('BLOC', 'Коммент к новости'), ('DOL', 'Список документов'), ('DOC', 'документ'), ('PHL', 'Список фотографий'), ('PHO', 'Фотография'), ('PHOC', 'Коммент к фотографии'), ('VIL', 'Список роликов'), ('VID', 'Ролик'), ('VIDC', 'Коммент к ролику')], default='', max_length=5, verbose_name='Класс объекта'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wall',
            name='object_id',
            field=models.PositiveIntegerField(default=0, verbose_name='id объекта'),
        ),
        migrations.AddField(
            model_name='wall',
            name='type',
            field=models.CharField(choices=[('USE', 'Пользователь'), ('COM', 'Сообщество'), ('MUL', 'Плейлист'), ('MUS', 'Трек'), ('ELN', 'Активность'), ('ELNC', 'Коммент к активности'), ('BLO', 'Новость'), ('BLOC', 'Коммент к новости'), ('DOL', 'Список документов'), ('DOC', 'документ'), ('PHL', 'Список фотографий'), ('PHO', 'Фотография'), ('PHOC', 'Коммент к фотографии'), ('VIL', 'Список роликов'), ('VID', 'Ролик'), ('VIDC', 'Коммент к ролику')], default='', max_length=5, verbose_name='Класс объекта'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='notify',
            name='verb',
            field=models.CharField(choices=[('ITE', ' разместил'), ('COM', ' прокомментировал'), ('WCOM', ' прокомментировала'), ('GCOM', ' прокомментировали'), ('REP', ' ответил на'), ('WREP', ' ответила на'), ('GREP', ' ответили на'), ('LIK', ' оценил'), ('WLIK', ' оценила'), ('GLIK', ' оценили'), ('DIS', ' не оценил'), ('WDIS', ' не оценила'), ('GDIS', ' не оценили'), ('INE', ' считает, что'), ('WINE', ' считает, что'), ('GINE', ' считает, что'), ('LCO', ' оценил'), ('WLCO', ' оценила '), ('GLCO', ' оценили'), ('LRE', ' оценил'), ('WLRE', ' оценила'), ('GLRE', ' оценили'), ('SVO', ' участвовал в опросе'), ('WSVO', ' участвовала в опросе'), ('GSVO', ' участвовали в опросе'), ('CRE', ' подал заявку в'), ('WCRE', ' подала заявку в'), ('GCRE', ' подали заявку в'), ('CCO', ' принят в'), ('WCCO', ' принята'), ('GCCO', ' приняты'), ('REG', ' зарегистрировался'), ('WREG', ' зарегистрировалась'), ('GREG', ' зарегистрировались')], max_length=5, verbose_name='Тип уведомления'),
        ),
        migrations.AlterField(
            model_name='wall',
            name='verb',
            field=models.CharField(choices=[('ITE', ' разместил'), ('COM', ' прокомментировал'), ('WCOM', ' прокомментировала'), ('GCOM', ' прокомментировали'), ('REP', ' ответил на'), ('WREP', ' ответила на'), ('GREP', ' ответили на'), ('LIK', ' оценил'), ('WLIK', ' оценила'), ('GLIK', ' оценили'), ('DIS', ' не оценил'), ('WDIS', ' не оценила'), ('GDIS', ' не оценили'), ('INE', ' считает, что'), ('WINE', ' считает, что'), ('GINE', ' считает, что'), ('LCO', ' оценил'), ('WLCO', ' оценила '), ('GLCO', ' оценили'), ('LRE', ' оценил'), ('WLRE', ' оценила'), ('GLRE', ' оценили'), ('SVO', ' участвовал в опросе'), ('WSVO', ' участвовала в опросе'), ('GSVO', ' участвовали в опросе'), ('CRE', ' подал заявку в'), ('WCRE', ' подала заявку в'), ('GCRE', ' подали заявку в'), ('CCO', ' принят в'), ('WCCO', ' принята'), ('GCCO', ' приняты'), ('REG', ' зарегистрировался'), ('WREG', ' зарегистрировалась'), ('GREG', ' зарегистрировались')], max_length=5, verbose_name='Тип уведомления'),
        ),
    ]
