# Generated by Django 3.2 on 2021-05-14 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0002_communityfollow'),
        ('notify', '0004_auto_20210420_1642'),
    ]

    operations = [
        migrations.AddField(
            model_name='notify',
            name='action_community',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='communities.community', verbose_name='Сообщество'),
        ),
        migrations.AddField(
            model_name='notify',
            name='community',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='communities.community', verbose_name='Сообщество'),
        ),
        migrations.AddField(
            model_name='wall',
            name='action_community',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='communities.community', verbose_name='Сообщество'),
        ),
        migrations.AddField(
            model_name='wall',
            name='community',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='communities.community', verbose_name='Сообщество'),
        ),
    ]
